= Climbing
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2018-09-05
:root: ../../
:description: This is the Climbing skill individual file.
include::{root}Include.adoc[]

.*_Attributes: Strength_*

While adventuring, there could be many reason that a [lexicWord]#character# would need to [lexicWord]#climb#.
It could be scaling a castle wall, getting down a sheer cliff or simply getting up a tree, it all falls under the [lexicWord]#climbing skill#.

== Climbing in Action Tempo

If a [lexicWord]#character# needs to climb while it is important to keep track of precise timing, the [lexicWord]#player# must do a [lexicWord]#climbing test# each [lexicWord]#round#.
The type of structure, surface or the environmental conditions will grant [lexicWord]#malus# to the climber.

* Type of structure/surface
** Numerous grips (ex: tree with a lot of branches, pile of rubble): +0
** Few grips (ex: trees trunk with no branches, jagged cliff): -1
** Flat surface (ex: man-made wall, sheer cliff): -2

* Environmental condition (ex: wet, frozen or friable surface): -2

For every [lexicWord]#hit# scored on the [lexicWord]#roll#, the [lexicWord]#character# can move 1 metres.

If a [lexicWord]#character# is ending up with a negative amount of [lexicWord]#MoSes#, he will fall.
Fall damage should be applied.

If a [lexicWord]#character# is not taking any action that require a dice [lexicWord]#roll#, he doesn't have to roll to not fall but he can't move either.

Note that a structure can change quality as the [lexicWord]#character# climbs it; a tree can have a naked trunk for the first few metres and then have many branches, or a cliff could have a pile of rubble at his base before transitioning to a sheer cliff.

== Climbing in Transaction Tempo

If a [lexicWord]#character# needs to climb while it is not primordial to follow the exact timing of the climb but just to see if he succeeded or not, the [lexicWord]#test# should be done as a [lexicWord]#first-fail rolling climbing test#.

The same [lexicWord]#malus# should be applied as defined in the previous section.

The [lexicWord]#player# will have to accumulate a number of [lexicWord]#MoSes# equal to the eight of the cliff in metre.
If he fails to do so, the [lexicWord]#character# falls a number of metre equal to the number of [lexicWord]#MoSes# accumulated so far.

If a [lexicWord]#character# is trying to climb a very tall cliff and the [ledxicWord]#GM# nor the [lexicWord]#player# want to make a large ammount or [lexicWord]#rolls#, the [lexicWord]#GM# can decide that each [lexicWord]#hits# allow the [lexicWord]#character# to climb a few meters (could be 3, 10, or anything that will still require the [lexicWord]#player# to make a few [lexicWord]#rolls#).
