= Improving Skills and Attributes
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2017-12-09
:root: ./
:description: This is the description of mechanics to improve ailities and skills.
include::Include.adoc[]

[lexicWord]#Experience# is gained per [lexicWord]#skills# and per [lexicWord]#attributes# and cannot be transferred.

== Improving Skills

A [lexicWord]#character# can gain [lexicWord]#experience# for his [lexicWord]#skills# in a few different ways:

* Rolling a [lexicWord]#flawless success# grant 1 [lexicWord]#experience point# in the [lexicWord]#skill# used.

* Rolling a [lexicWord]#complete failure# could gain an [lexicWord]#experience point# if the [lexicWord]#player# succeed at a [lexicWord]#Confidence & ego# test.
Details in the [lexicWord]#complete failure# section.

* Finally, the [lexicWord]#GM# is free to award [lexicWord]#experience points# to a [lexicWord]#player# when this one uses a [lexicWord]#skill# in an original manner to advance a significant plot point.

A [lexicWord]#player# can raise the [lexicWord]#rank# of a [lexicWord]#skill# at any moment by spending an amount of [lexicWord]#experience points# linked to that [lexicWord]#skill# equal to the current [lexicWord]#rank# of the [lexicWord]#skill# (including the [lexicWord]#group's rank#) plus 1, multiplied by 4.

.Example
[caption = ""]
====
A [lexicWord]#skill# at a [lexicWord]#rank# of 2 will cost 12 [lexicWord]#experience points# ((2 + 1) * 4) to be raised to a [lexicWord]#rank# of 3.
====

== Improving Skill Groups

When 3 [lexicWord]#skills# in a [lexicWord]#group# have at least one [lexicWord]#rank# (not including the [lexicWord]#group's rank#), they must be each reduced by one [lexicWord]#rank# to increase the [lexicWord]#rank# of the [lexicWord]#group# by one.

.Example
[caption = ""]
====
A [lexicWord]#character# with [lexicWord]#climbing# 2, [lexicWord]#running# 1 and [lexicWord]#jumping# 1, all under the [lexicWord]#athleticism group#, must subtract 1 from those three [lexicWord]#skills#, bringing them back to [lexicWord]#climbing# 1, [lexicWord]#jumping# and [lexicWord]#running# 0 to increase [lexicWord]#athleticism# bt 1.
This will not affect the [lexicWord]#dice-pool# of any of the three [lexicWord]#skills# which were part of the trade, but it will increase the [lexicWord]#dice-pool# of the other two [lexicWord]#skills# under [lexicWord]#athleticism#, [lexicWord]#lifting# and [lexicWord]#swimming#.
====
////
[lexicWord]#Skills# subdivided in [lexicWord]#specialities# does not directly gain [lexicWord]#experience#, but [lexicWord]#experience# is attributed to the [lexicWord]#speciality# being tested.

[lexicWord]#speciality ranks# are raised in the same manner as the [lexicWord]#skills#, but the [lexicWord]#rank# of the [lexicWord]#parent skill# should always be added to the [lexicWord]#rank# of the [lexicWord]#speciality# for calculation of the cost.

.Example
[caption = ""]
====
A [lexicWord]#speciality# with a [lexicWord]#rank# of 2, governed by a [lexicWord]#parent skill# with a [lexicWord]#rank# of 2, would cost 20 [lexicWord]#experience points# ((2 + 2 + 1) * 4) to increase.
====

[lexicWord]#Skills# subdivided in [lexicWord]#specialites# are raised by lowering the rank of three different [lexicWord]#specialities# by 1 to raise the [lexicWord]#parent skill# rank by 1.

.Example
[caption = ""]
====
A [lexicWord]#character# with an [lexicWord]#athleticism# rank of 1, with the [lexicWord]#specialities# [lexicWord]#climbing# 2, [lexicWord]#running# 1 and [lexicWord]#jumping# 1, can subtract 1 from those three [lexicWord]#specialities#, bringing back [lexicWord]#climbing# to 1, [lexicWord]#jumping# and [lexicWord]#running# to 0 to increase [lexicWord]#athleticism# to 2.
This will not affect the [lexicWord]#dice-pool# of any of the three [lexicWord]#specialities# which were part of the trade, but it will increase the [lexicWord]#dice-pool# of the other two [lexicWord]#athleticism# [lexicWord]#specialities#, [lexicWord]#lifting# and [lexicWord]#swimming#.
====
////

== Improving Attributes

One point of [lexicWord]#attribute experience# is gained by rolling the highest number possible on at least one die in a [lexicWord]#roll#.
Only one point of [lexicWord]#attribute experience# can be gained per roll.

.Example
[caption=""]
====
A [lexicWord]#character# with [lexicWord]#cooking# 2 and a [lexicWord]#wisdom# of 8 would have a [lexicWord]#dice-pool# of 3d8.
If one or more of those 3 dice shows a 8, the [lexicWord]#player# can mark one [lexicWord]#wisdom experience point#.
====

An [lexicWord]#attribute# can be raised by one [lexicWord]#rank# by spending a number of [lexicWord]#experience points# equal to the current [lexicWord]#rank# of the [lexicWord]#attribute#.

.Example
[caption=""]
====
A [lexicWord]#character# with a [lexicWord]#wisdom# of 8 will need to spend 8 [lexicWord]#wisdom experience points# to increase it to 9.
====
////
Every time a [lexicWord]#player# uses [lexicWord]#experience# to raise the level of a [lexicWord]#skill# or of a [lexicWord]#speciality#, he can add 2 [lexicWord]#experience points# in the [lexicWord]#attribute# governing this [lexicWord]#skill#.
If this [lexicWord]#skill# is governed by more than one [lexicWord]#attribute#, the [lexicWord]#experience# can be split between two governing [lexicWord]#attributes#.

[lexicWord]#Attributes# can be raised by spending an amount of [lexicWord]#experience points# equal to the current level of the [lexicWord]#attribute#.

.Example
[caption = ""]
====
An [lexicWord]#attribute# with a [lexicWord]#rank# of 10 will cost 10 [lexicWord]#experience points# to be raised to 11.
====

Some [lexicWord]#traits# can be purchased using [lexicWord]#skill# or [lexicWord]#attribute experience points#.
Details will be provided in the [lexicWord]#character creation# section.

Lowering [lexicWord]#specialities ranks# to increase their [lexicWord]#parent skill# does not give [lexicWord]#attribute experience#.
////

== Mentoring

A [lexicWord]#character# can help another improve a [lexicWord]#skill# by [lexicWord]#mentoring#.
The mentor’s [lexicWord]#skill rank# must be above the [lexicWord]#skill rank# of the apprentice by at least 2 [lexicWord]#ranks#.

When the mentor uses the [lexicWord]#skill# to perform a task, the apprentice has a chance of [lexicWord]#gaining experience# in this [lexicWord]#skill#.

If the task is of a type which can be [lexicWord]#assisted#, the apprentice must assist with their own [lexicWord]#dice-pool#.
Whenever the mentor rolls a [lexicWord]#flawless success#, both him and the apprentice gain an [lexicWord]#experience point# in the [lexicWord]#skill#.
If the apprentice rolls a [lexicWord]#flawless success#, the normal rule applies.

If the task is one where [lexicWord]#assistance# is impossible or impractical, the apprentice must look closely.
If the mentor rolls a [lexicWord]#flawless success#, the [lexicWord]#experience point# can be attributed to the apprentice instead of to the mentor (at the mentor's discretion)

== Training and sparing

Two [lexicWord]#characters# can work together to improve [lexicWord]#skills# which require [lexicWord]#opposed test# (which can be the same or two different [lexicWord]#skills#).

The two [lexicWord]#characters# each make their roll normally but, whenever one of them rolls a [lexicWord]#flawless success#, both earn an [lexicWord]#experience points# in the respective [lexicWord]#skill# they were training.

Sparing is training for combat [lexicWord]#skills#.
The rules are the same as for regular combat but damage is not rolled and [lexicWord]#spirit# lose is halved.
In the similar way as in training, if one [lexicWord]#character# score a [lexicWord]#flawless success#, both him and the [lexicWord]#character# against who the hit has been scored earn an [lexicWord]#experience point#.

Sparing is not limited to two [lexicWord]#characters# at a time, but only the [lexicWord]#character# scoring the [lexicWord]#flawless success# and the [lexicWord]#character# against whom it has been scored will gain [lexicWord]#experience#.
