= Prologue
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2017-12-09
:root: ./
:description: This is the introduction of the book, what is a RPG, who am I, etc.
include::Include.adoc[]

<<<

[partintro]
== Introduction
'''

My name is {author}.
I am the creator of [lexicWord]#{gameName}# and the [lexicWord]#SdA system# and I would like to begin this publication by thanking you for your interest in this book.
I hope you and your friends will get countless hours of enjoyment and excitement from this game.
Make sure to visit our website at {webAddress} for printable character sheets, cheat sheets and other game help.

'''

=== What is a Role Playing Game?

The chances are that most of you are already familiar with the concept of role-playing game (RPG), but it seems to be a tradition that every RPG book start with an explanation of what is an RPG.

If you have picked up this book without any prior knowledge of what it is about, hopefully this section will enlighten you.
If you are a veteran role player, you may safely skip this section, but reading it might give you a clue as to how I perceive role-playing.

A role-playing game, as the name indicates, is a game where you play a role.
Players each create a [lexicWord]#character# with their own personality, qualities, flaws, history, [lexicWord]#skills#, etc.
Those [lexicWord]#characters# (refered to as [lexicWord]#Player Character# or [lexicWord]#PC#) will venture together, overcome obstacles, gather treasures, defeat villains, become villains, save the day, fail and, sometimes, die.

Unlike most games, the players don't compete against each other and there are no winners and losers.
Role playing games are fundamentally collaborative group games.
There is no well define goal to reach, number of points to get or conditions for victory; the goal of the game is to create an interesting and entertaining story as a group, and the only way to “win the game” is to have fun.

Since there is no clear end-point in a role-playing game, the length of the games can vary greatly; some will last for a few hours, but most games will extend on many play sessions of a few hours each and can end up lasting years!

'''

=== The Game Master

(((Game Master, GM)))
Another big particularity of RPGs is that one of the player hold a special role: the Game Master ([lexicWord]#GM#).
Unlike the other players, the [lexicWord]#GM# does not play a specific [lexicWord]#character# but will give life to all the supporting cast and antagonists the [lexicWord]#PCs# will meet and face.
Those [lexicWord]#characters# are called [lexicWord]#non-player characters# or [lexicWord]#NPCs#.

The [lexicWord]#GM# also create and populate the world in which the adventures take place and will describe the scenery and events of this world to the other players.
The [lexicWord]#GM# has the responsibility to prepare some kind of adventure for the [lexicWord]#PCs#, propose hooks to allow them to jump on such adventures and present them with encounters and challenges to overcome.

The [lexicWord]#GM# will also act as a referee for the game.
In a RPG, [lexicWord]#PCs# can attempt to do almost anything.
Sooner or later, every [lexicWord]#GM# will be made aghast by the plans and ideas of their players.
It would be impossible to try to cover every situation with a clear-cut rule describing how it is to be resolved.
This is where the [lexicWord]#GM# as adjudicator comes in; [lexicWord]#GMs# have the responsibility to interpret the rules and decide how the intentions of the players can be translated to the available game mechanics.

[lexicWord]#GMs# also hold a veto on everything in the game.
They can decide to change or ignore a rule or to declare a player's scheme to be unrealistic and not allow it.
This power should be used with parsimony and restraint; if you want to alter or disregard a rule, make sure to discuss about it with your player before encountering a situation where this rule is called upon (ideally before starting playing).
If a player wants his [lexicWord]#character# to accomplish some crazy actions, instead of saying a strict no, the [lexicWord]#GM# can try to tweak the idea with him to try to bring it back to an appropriate level of realism for the game being played or make the endeavour extremely unlikely to succeed.
If the [lexicWord]#GM# decides to take this later road, once he allowed a player to go ahead and attempt the action, even if he decided on a difficulty level he was sure would make the [lexicWord]#character# fail, if this last one succeed by good fortune, the [lexicWord]#GM# needs to let the deed be completed; it is now to late for veto.

Being the [lexicWord]#GM# of a group represent more work, but is extremely gratifying.
You get to create a world and present it to the other players, control many [lexicWord]#characters#, and take your friends on great adventures.

Although it is the job of the [lexicWord]#GMs# to bring resistance to the [lexicWord]#player characters#, they do not themselves oppose the players; a [lexicWord]#GM# and his players work together to create a vivid story.
For this narrative to be interesting it will need challenges to overcome and this is the main responsibility of the [lexicWord]#GM#.

'''

=== What Material Do You Need to Play RPGs?

(((Dice, Polyhedral Dice, Material)))
In order to play a role-playing game in general, you will need pencils, erasers, paper and dice.
Some specific games require special material like playing cards, tokens, jenga(TM) blocks, etc.

To play [lexicWord]#{gameName}# specifically, all you need is the basic material required by most RPGs: something to write with, something to write on and [lexicWord]#polyhedral dice#.

[lexicWord]#Polyhedral dice# are dice of various shapes and number of faces.
The classic set of [lexicWord]#polyhedral dice# comes with 6 or 7 dice and include one die with 4 faces (d4, shaped as a pyramid), one die with 6 faces (d6, the cube used by so many board games), one die with 8 faces (d8), one or two dice with 10 faces (d10, when two are included, one will usually be marked with “00”, “10”, “20”, “30”,... , up to “90”; this dice is sometime referred to as a percentile die, d% or d00), one die with 12 faces (d12) and one die with 20 faces (d20).
[lexicWord]#{gameName}# uses all those dice (except for the percentile one) and it would facilitate play to own a few full sets.

Although they are not required, many groups use miniatures for a visual representation of combats and other situations where knowing the precise position of each member of the party is important.
Of course, any kind of distinctive token can be used in place of miniatures.
Some groups will otherwise completely forgo the use of such visual aids and rely completely on imagination and expansive descriptions.
There is no right or wrong answer here and it is a simple matter of preferences.

The most important thing you will need to partake in a RPG is at least one other person.
A minimum of two [lexicWord]#players# is required to engage in the game; one will impersonate a [lexicWord]#character#, the other will take on the role of [lexicWord]#GM#.

'''

=== Why I Play RPGs And Why You Should Give it a Try?

There is no other type of games out there that give you more freedom than role playing games.
In RPGs, you are truly solely limited by your and your friends' imagination.
Video games can be a great hobby but your options will always be limited by what the developers thought off (or by the bugs they left in that you can exploit).
Board games are also a lot of fun but you have clearly defined actions you can do and strict rules framing and narrowing your possibilities.

In role-playing games, you can have your [lexicWord]#characters# attempt to do almost anything (which doesn't mean they're going to succeed).
Whenever you face an obstacle, the obvious solution is not always the best and the optimal approach can be different from [lexicWord]#character# to [lexicWord]#character#.
RPGs really encourage the [lexicWord]#players# to think outside of the box and [lexicWord]#GMs# should rewards imaginative solutions (as long as they are realistic in the [lexicWord]#game world# the [lexicWord]#GM# designed).

Role playing games are also a good way to spend some social time with live people, away from a screen (of course, nowadays you can play online through video call but at least you are looking at someone's face).
The fact that RPGs have so little limits regarding the actions you can attempt and the stories you can devise, each game will be truly unique and should create long-lasting shared memories with friends.

There are other benefits from playing role-playing games that may be more specific to certain situations.
Since playing RPGs is about getting into the skin of somebody else (your [lexicWord]#character#), it can help develop empathy and I believe empathy is what will save the world (or the lack thereof will doom it).

There is also many stories of stutterers who, while impersonating their [lexicWord]#character#, lose their stutter, and sometimes, like in my own personal case, they can learn to lose it in everyday life as well.  Good riddance!

Role playing game can also be a fantastic teaching and learning tool.
They can be used with children to have them solve problems in an engaging way, or to help them realize that their actions have consequences.
It can also be used among adults to explore different “what if” scenarii or philosophical ideas and bring them to their logical conclusions in a ludic manner.

RPGs can also help anybody playing them develop their imagination, confidence and outgoingness as well as their problem solving, creative writing, improvisation and acting skills.

'''

=== What Qualities Do You Need to Play RPGs?

The only quality you really need to take part in a role-playing game is the capacity to spend a few hours with your fellow [lexicWord]#players# without arguing and fighting over menial things.

Being imaginative and outgoing help but don't worry if you are not; those qualities will develop over time as you play.

Playing [lexicWord]#{gameName}# may require you to do some additions and subtractions but I tried to keep those to a minimum and to keep every calculation very simple.
The maths involved should be accessible to everybody able to count to fifty and then some.

So, if you are able to spend an evening with some friends without it devolving into chaos and violence, congratulations, you have what it takes to play a role-playing game.

'''

=== Why Did I Create this System and Wrote this Book?

There is many role-playing systems (rule set) and games out there and a lot of them are really good, so why create a new one?
Because there are many systems out there containing wonderful ideas.
I admit it, I shamelessly pillage a lot of ideas from my favourite RPG systems, tweaked them and mashed them together to create [lexicWord]#{gameName}#.
I then added some of my own original ideas that I came up with over my decades of playing RPGs.

I also had the desire to create a more realistic system than many popular RPGs, while keeping it simple enough so the play is not bogged down with rules and details and slowed to a crawl.

While developing the [lexicWord]#SdA system#, I tired to homogenize the rules as much as possible for the [lexicWord]#players# to have just a handful of mechanics to learn.
The vast majority of times, whenever they have to attempt something requiring a dice roll, the same mechanic is going to be used; almost everything in the [lexicWord]#SdA system# is a [lexicWord]#skill check#.

The name [lexicWord]#SdA# refers to the way most RPGs using polyhedral dice describe the number and type of dice to roll.
It is traditional to describe a dice roll by the number of dice to be roll, the letter "d" and the type of dice to be used (the number of faces).
5d6 means to roll 5 dice with 6 faces.
The “S” in SdA represents the [lexicWord]#skill# level (+1) the [lexicWord]#player# is about to test and the “A” represent the [lexicWord]#attribute# governing this [lexicWord]#skill#.

.Example
[caption = ""]
====
A [lexicWord]#character# with an [lexicWord]#acrobatics# [lexicWord]#skill# of 2 and an [lexicWord]#agility# (the [lexicWord]#attribute# governing [lexicWord]#acrobatics#) of 6, will roll 3d6 whenever they need to test their [lexicWord]#acrobatics#.
One die is always added to the level of the [lexicWord]#skill#, so a [lexicWord]#skill# of 0 would still allow one die to be rolled.
====

Attacking someone, using magic, resisting the effect of a spell or from the elements, preparing a feast will all work in the same manner; all those are [lexicWord]#skills# based.

The reason I went with this dice system is the good tactile feedback you get from the dice-pool and how it gives you an impression of the ability of your [lexicWord]#character#.
You can feel in your hand, before you roll, the difference between a task you are good at and one you are mediocre.
You can feel the varying odds of success, in you favour when you roll 5d12, not so much if you can only roll 1d4.

Amongst the other things in the [lexicWord]#SdA system# that distinguish it from other rule set you will find:

* A dynamic and strategic combat system base of choice and trade-off

* Damage and [lexicWord]#injuries# with consequences

* A variety of weapon and armour type with implications beyond the cosmetic

* [lexicWord]#Characters# not defined by a class but by their lived experience

* Progression not based on levels but on what the [lexicWord]#characters# do and what [lexicWord]#skills# they use.

Most of those mechanics exist in other systems in one way or another, I recognize that, but I wanted to bring them all together in harmony, in a coherent and easy to learn manner.

'''

=== Rules or Guidelines

The goal of role-playing games usually is to collaboratively create a story where the [lexicWord]#player character# are the protagonists.
The [lexicWord]#players# and [lexicWord]#GM#, should work together towards this goal.
If the rules get in the way of the story, the [lexicWord]#GM# can decide to put them aside, tweak them, bend them.

At the start of a new campaign, feel free to have a discussion amongst your group and decide if some rules are going to be ignores or modified.
Those changes are referred to as "house rules" or "homebrew".
If you realize that those alterations are a detriment to the game, don't hesitate to take a moment to re-open the conversation with your group, preferably not mid-session.

Of course, every adjustment of the rules need to be approved by the [lexicWord]#GM#.
[lexicWord]#GMs# always have the last word when it comes to guidelines interpretation, adaptation or abolition.

There is a maxim that is often considered to apply to all [lexicWord]#RPGs#: the "rule zero", sometimes referred to as "the rule of cool".
This 0th rule suggest that, since [lexicWord]#RPGs# are entertainment, the group should do whatever is necessary to make the game as entertaining as possible.
If a [lexicWord]#player# or the [lexicWord]#GM# suggest something that is not strictly by the rules as written (RaW) but is truly awesome, just go with it.

Of course, if the "rule of cool" is invoked too frequently, it will lose it's impact.
As it is for spice, a touch can improve a meal, but too much will spoil it.
Like in most things, it is a matter of balance.

The right amount of adherence to the RaW will vary from group to group.
You will, over time, find the style of play that is right for you, that you enjoy the most.

In reason of the flexibility of the rules, they could be seem more as guidelines.
This does not mean that they should be seen as mere suggestions; a great amount of thoughts and considerations has been put in the conception of this system to offer engaging experiences.

Remember that [lexicWord]#RPGs# are intended to be games; if you completely ignore the rules, you'll lose that aspect of the activity.

'''

=== Exposing my Biases

The [lexicWord]#SdA system# has been design in a way to allow a variety of style of play, from epic fantasy game to more tone done gritty one.
The power level of the [lexicWord]#player character# can easily be scale to fit the type of game your group enjoy the most.
However, despite my effort to minimize my biases towards one type of play, some will inevitably find their way in this tome.
For the sake of transparency, I decided to be upfront about those inclinations.
This is not done to push you towards a specific type of play, but it might help explain some design decisions I made.

==== Magic

I always preferred setting where magic is rare, strange and scary and only a few people can practice it.
Maybe it has to be kept underground, without the authorities or the non-initiated finding out.
The unbegun are unable to make the distinction between the different types or sources of magic.

If the setting proposes a world where magic is ubiquitous, the implication of such powers should be accounted for.
Those ramifications would be far reaching and impact every aspect of life from food production to political structures.

==== Power Level

I tend to enjoy a type of game where the [lexicWord]#player characters# begins their adventures barely more competent than the average person of the setting, just slightly above average.
I believe that what makes someone a hero is not having exceptional powers, but acting in an exceptional way in critical situations.
Experiencing the growth of a character from humble beginnings to super-human capabilities.

==== Scope

I can see the appeal of epic game where the [lexicWord]#PCs# have to save the world from a great evil.
I, however, always preferred more toned-down campaigns, where [lexicWord]#characters# pursue more personal goals.
My predilections are towards narrative where the heroes are mostly good, but confronted to morally grey situations.
Those kinds of scenarii are a good opportunity to explore different philosophical concepts and their logical conclusions.

==== Combats

In my opinion, violence in [lexicWord]#RPGs# should be treated seriously.
Combats are better when deadly and force players to think twice before engaging their [lexicWord]#characters# in bloodshed.

Representing skirmishes using miniatures and a grid facilitates the exercise.
It prevents confusions and allows the [lexicWord]#players# to use more elaborate tactics.

I tend to prefer hexagonal grid, having the [lexicWord]#characters# facing a point of the hexagon (instead of an edge).
In this configuration, out of the six hexes surrounding a [lexicWord]#character#, two are considered the front, two are in the rear and two are on the sides (one each).

Square grids have the advantage of fitting well with most artificial structures (usually built in rectangle shape).
They do come with the inconvenient of making diagonal movement messy.

Nothing prevent a group to use both systems in their campaign; hexagonal grids for wilderness encounters and square one for interior ones.

==== Racial Bias

Here, I must admit to the shameful fact that I possess racial prejudices... when it comes to fantasy races.

Since playing Warcraft(TM) has a youth, I always had a soft sport for Orcs and Goblins.

On the other hand, Elves usually bore me (although, I'm happy with the spin I gave them in this game).

I tried to keep all the difference races as balanced as possible.
Perfect evenness can never be achieved since the potency of a different features is dependent upon the setting and type of game you're engaging in.

In the end, I don't believe that any race is absolutely better or worse than the rest.
Each have their own advantages and drawbacks.
I might find some cooler than the others, but your opinion might (and hopefully will) vary.

Obviously, the races (species would be a better term) depicted in this book are from the realm of fantasy.
None of them represent any real-world racial or cultural group.

'''

=== About the Organization of this Book

I tried to present the information in this book in the manner that made the most sense to me.

Following this introduction, I'll present the basic rules that everybody should master.
After reading this section, if you were to be handed a pregenerated [lexicWord]#character# (some can be found on our website), you would know enough to begin play.

Playing a pregenerated [lexicWord]#character# could allow you to quickly jump into the action, but creating your own is a big part of the fun or [lexicWord]#RPGs#.
The section concerning [lexicWord]#character# creation will imediatly follow the presentation of the basic rules.

If the [lexicWord]#character# you created is a magic user, you'll have to pay some attention to the spell section.

The adventuring section contains the more circumstantial rules that might not be relevant in every session.
It would be good if the [lexicWord]#GM# and maybe at least one other [lexicWord]#player# would be familiar with those rules, at least enough to know they exist and to be able to reference them quickly if need be.

The following two sections are the purview of the [lexicWord]#GM#.
The bestiary presents a variety of creature to populate the world with.
They can be used to offer opposition as well as support to the [lexicWord]#players#.

The GMing section is a collection of advice about preparing and running the game.
Experienced [lexicWord]#GMs# in other [lexicWord]#RPGs# might not get much from it, but, it you are new to the activity, you'll sure find some valuable insight.

At the end of the book, you'll find an appendices section.
Once you're familiar with the rules, you should basically be able to run the game completely from those appendices.

'''

=== About the Writing Style of this Book

My focus while writing this book was to be as clear as possible.
When I had to make the choice between style and clarity, I went with the later.
This might leave the prose a little dry, but I believe it makes the rules easier to digest.

You'll notice that the [lexicWord]#SdA system# design is based on the metric system.
Movement and weapon ranges are calculated in metres, weights are calculated in kilograms and temperatures in Celsius.

I decided to favour the metric system over the imperial one for its international adoption and simplicity.
Even someone who has never been exposed to the metrics systems can grasp its way of being subdivided rather quickly.
Admittedly, having a good mental representation of the different distances, weights and temperatures described might take some time getting used to.

Remembering that 16 ounces make a pound and 14 pounds make a stone but 12 inches make a foot while 3 feet make a yard but it takes 1760 yards to make a mile can be confusing, even for people used to the imperial system.

The metric system also avoid confusion when decimal notations are used.
5.3 pounds is actually 5 pounds and 4 ounces and 6 drachms and 1 scruple and some minims.
This is far from intuitive.
And this is not even mentioning the possible confusion between ounces and troy ounces!

If you categorically refuse to use the metric system, a conversion chart is available at the end of the book with corresponding measurement, not exact, but close enough to not break the system and simple enough to calculate mentally (1 metre become 3 feet instead of 3 feet and 3 inches, a.k.a 3¼ or 3.25 feet).

'''
<<<

== Terms Definition

As you might have already noticed in this introduction, some terms are written in italics.
This is an indication that the term is used in a precise way to refer to a specific element of the game.
Those terms will be explained as they are introduced and their definition can also be found in the glossary at the end of this book.
Some of the terms are so fundamentals that I will define them below.
If you are familiar with [lexicWord]#RPGs#, those terms should already be known.

[glossary]
Attributes::
The physical and mental aptitudes of a character.  6 attributes compose a character: Agility, Constitution, Strength, Erudition, Persona and wisdom.

Character::
A character refers to an individual in the game world, either controlled by the GM (NPC) or by another player (PC).  This include humanoids, animals and monsters.

GM (Game Master)::
A player fulfilling a special role of describing the scene, impersonating the characters not controlled by the other players and acting as a referee.

Player::
The term player refers to a real world person sitting at the table, either controlling an in-game character or being the GM.

Skills::
Represent the different levels of proficiency a character can perform actions.

Test (Skill Test)::
Whenever a player attempts an action that could succeed or fail (and if there is dramatic outcome to success or failure), a skill test can be requested by the GM.
Different types of test exist for different situations and each one will be covered later in this book.

'''
