= Prologue
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2017-12-09
:root: ./
:description: This is the introduction of the book, what is a RPG, who am I, etc.
include::Include.adoc[]

<<<

[partintro]
== Introduction
'''

My name is {author}.
I am the creator of [lexicWord]#{gameName}# and the [lexicWord]#SdA system# and I would like to begin this publication by thanking you for your interest in this book.
I hope you and your friends will get countless hours of enjoyment and excitement from this game.
Make sure to visit our website at {webAddress} for printable character sheets, cheat sheets and other game help.

'''

=== What is a Role Playing Game?

The chances are that most of you are already familiar with the concept of role-playing game (RPG), but it seems to be a tradition that every RPG book start with an explanation of what is an RPG.

If you have picked up this book without any prior knowledge of what it is about, hopefully this section will enlighten you.
If you are a veteran role player, you may safely skip this section, but reading it might give you a clue as to how I perceive role-playing.

A role-playing game, as the name indicates, is a game where you play a role.
Players each create a [lexicWord]#character# with their own personality, qualities, flaws, history, [lexicWord]#skills#, etc.
Those [lexicWord]#characters# (refered to as [lexicWord]#Player Character# or [lexicWord]#PC#) will venture together, overcome obstacles, gather treasures, defeat villains, become villains, save the day, fail and, sometimes, die.

Unlike most games, the players don't compete against each other and there are no winners and losers.
Role playing games are fundamentally collaborative group games.
There is no well define goal to reach, number of points to get or conditions for victory; the goal of the game is to create an interesting and entertaining story as a group, and the only way to “win the game” is to have fun.

Since there is no clear end-point in a role-playing game, the length of the games can vary greatly; some will last for a few hours, but most games will extend on many play sessions of a few hours each and can end up lasting years!

'''

=== The Game Master

(((Game Master, GM)))
Another big particularity of RPGs is that one of the player hold a special role: the Game Master ([lexicWord]#GM#).
Unlike the other players, the [lexicWord]#GM# does not play a specific [lexicWord]#character# but will give life to all the supporting cast and antagonists the [lexicWord]#PCs# will meet and face.
Those [lexicWord]#characters# are called [lexicWord]#non-player characters# or [lexicWord]#NPCs#.

The [lexicWord]#GM# also create and populate the world in which the adventures take place and will describe the scenery and events of this world to the other players.
The [lexicWord]#GM# has the responsibility to prepare some kind of adventure for the [lexicWord]#PCs#, propose hooks to allow them to jump on such adventures and present them with encounters and challenges to overcome.

The [lexicWord]#GM# will also act as a referee for the game.
In a RPG, [lexicWord]#PCs# can attempt to do almost anything.
Sooner or later, every [lexicWord]#GM# will be made aghast by the plans and ideas of their players.
It would be impossible to try to cover every situation with a clear-cut rule describing how it is to be resolved.
This is where the [lexicWord]#GM# as adjudicator comes in; [lexicWord]#GMs# have the responsibility to interpret the rules and decide how the intentions of the players can be translated to the available game mechanics.

[lexicWord]#GMs# also hold a veto on everything in the game.
They can decide to change or ignore a rule or to declare a player's scheme to be unrealistic and not allow it.
This power should be used with parsimony and restraint; if you want to alter or disregard a rule, make sure to discuss about it with your player before encountering a situation where this rule is called upon (ideally before starting playing).
If a player wants his [lexicWord]#character# to accomplish some crazy actions, instead of saying a strict no, the [lexicWord]#GM# can try to tweak the idea with him to try to bring it back to an appropriate level of realism for the game being played or make the endeavour extremely unlikely to succeed.
If the [lexicWord]#GM# decides to take this later road, once he allowed a player to go ahead and attempt the action, even if he decided on a difficulty level he was sure would make the [lexicWord]#character# fail, if this last one succeed by good fortune, the [lexicWord]#GM# needs to let the deed be completed; it is now to late for veto.

Being the [lexicWord]#GM# of a group represent more work, but is extremely gratifying.
You get to create a world and present it to the other players, control many [lexicWord]#characters#, and take your friends on great adventures.

Although it is the job of the [lexicWord]#GMs# to bring resistance to the [lexicWord]#player characters#, they do not themselves oppose the players; a [lexicWord]#GM# and his players work together to create a vivid story.
For this narrative to be interesting it will need challenges to overcome and this is the main responsibility of the [lexicWord]#GM#.

'''

=== What Material Do You Need to Play RPGs?

(((Dice, Polyhedral Dice, Material)))
In order to play a role-playing game in general, you will need pencils, erasers, paper and dice.
Some specific games require special material like playing cards, tokens, jenga(TM) blocks, etc.

To play [lexicWord]#{gameName}# specifically, all you need is the basic material required by most RPGs: something to write with, something to write on and [lexicWord]#polyhedral dice#.

[lexicWord]#Polyhedral dice# are dice of various shapes and number of faces.
The classic set of [lexicWord]#polyhedral dice# comes with 6 or 7 dice and include one die with 4 faces (d4, shaped as a pyramid), one die with 6 faces (d6, the cube used by so many board games), one die with 8 faces (d8), one or two dice with 10 faces (d10, when two are included, one will usually be marked with “00”, “10”, “20”, “30”,... , up to “90”; this dice is sometime referred to as a percentile die, d% or d00), one die with 12 faces (d12) and one die with 20 faces (d20).
[lexicWord]#{gameName}# uses all those dice (except for the percentile one) and it would facilitate play to own a few full sets.

Although they are not required, many groups use miniatures for a visual representation of combats and other situations where knowing the precise position of each member of the party is important.
Of course, any kind of distinctive token can be used in place of miniatures.
Some groups will otherwise completely forgo the use of such visual aids and rely completely on imagination and expansive descriptions.
There is no right or wrong answer here and it is a simple matter of preferences.

The most important thing you will need to partake in a RPG is at least one other person.
A minimum of two [lexicWord]#players# is required to engage in the game; one will impersonate a [lexicWord]#character#, the other will take on the role of [lexicWord]#GM#.

'''

=== Why I Play RPGs And Why You Should Give it a Try?

There is no other type of games out there that give you more freedom than role playing games.
In RPGs, you are truly solely limited by your and your friends' imagination.
Video games can be a great hobby but your options will always be limited by what the developers thought off (or by the bugs they left in that you can exploit).
Board games are also a lot of fun but you have clearly defined actions you can do and strict rules framing and narrowing your possibilities.

In role-playing games, you can have your [lexicWord]#characters# attempt to do almost anything (which doesn't mean they're going to succeed).
Whenever you face an obstacle, the obvious solution is not always the best and the optimal approach can be different from [lexicWord]#character# to [lexicWord]#character#.
RPGs really encourage the [lexicWord]#players# to think outside of the box and [lexicWord]#GMs# should rewards imaginative solutions (as long as they are realistic in the [lexicWord]#game world# the [lexicWord]#GM# designed).

Role playing games are also a good way to spend some social time with live people, away from a screen (of course, nowadays you can play online through video call but at least you are looking at someone's face).
The fact that RPGs have so little limits regarding the actions you can attempt and the stories you can devise, each game will be truly unique and should create long-lasting shared memories with friends.

There are other benefits from playing role-playing games that may be more specific to certain situations.
Since playing RPGs is about getting into the skin of somebody else (your [lexicWord]#character#), it can help develop empathy and I believe empathy is what will save the world (or the lack thereof will doom it).

There is also many stories of stutterers who, while impersonating their [lexicWord]#character#, lose their stutter, and sometimes, like in my own personal case, they can learn to lose it in everyday life as well.  Good riddance!

Role playing game can also be a fantastic teaching and learning tool.
They can be used with children to have them solve problems in an engaging way, or to help them realize that their actions have consequences.
It can also be used among adults to explore different “what if” scenarii or philosophical ideas and bring them to their logical conclusions in a ludic manner.

RPGs can also help anybody playing them develop their imagination, confidence and outgoingness as well as their problem solving, creative writing, improvisation and acting skills.

'''

=== What Qualities Do You Need to Play RPGs?

The only quality you really need to take part in a role-playing game is the capacity to spend a few hours with your fellow [lexicWord]#players# without arguing and fighting over menial things.

Being imaginative and outgoing help but don't worry if you are not; those qualities will develop over time as you play.

Playing [lexicWord]#{gameName}# may require you to do some additions and subtractions but I tried to keep those to a minimum and to keep every calculation very simple.
The maths involved should be accessible to everybody able to count to fifty and then some.

So, if you are able to spend an evening with some friends without it devolving into chaos and violence, congratulations, you have what it takes to play a role-playing game.

'''

=== Why Did I Create this System and Wrote this Book?

There is many role-playing systems (rule set) and games out there and a lot of them are really good, so why create a new one?
Because there are many systems out there containing wonderful ideas.
I admit it, I shamelessly pillage a lot of ideas from my favourite RPG systems, tweaked them and mashed them together to create [lexicWord]#{gameName}#.
I then added some of my own original ideas that I came up with over my decades of playing RPGs.

I also had the desire to create a more realistic system than many popular RPGs, while keeping it simple enough so the play is not bogged down with rules and details and slowed to a crawl.

While developing the [lexicWord]#SdA system#, I tired to homogenize the rules as much as possible for the [lexicWord]#players# to have just a handful of mechanics to learn.
The vast majority of times, whenever they have to attempt something requiring a dice roll, the same mechanic is going to be used; almost everything in the [lexicWord]#SdA system# is a [lexicWord]#skill check#.

The name [lexicWord]#SdA# refers to the way most RPGs using polyhedral dice describe the number and type of dice to roll.
It is traditional to describe a dice roll by the number of dice to be roll, the letter "d" and the type of dice to be used (the number of faces).
5d6 means to roll 5 dice with 6 faces.
The “S” in SdA represents the [lexicWord]#skill# level (+1) the [lexicWord]#player# is about to test and the “A” represent the [lexicWord]#attribute# governing this [lexicWord]#skill#.

.Example
[caption = ""]
====
A [lexicWord]#character# with an [lexicWord]#acrobatics# [lexicWord]#skill# of 2 and an [lexicWord]#agility# (the [lexicWord]#attribute# governing [lexicWord]#acrobatics#) of 6, will roll 3d6 whenever they need to test their [lexicWord]#acrobatics#.
One die is always added to the level of the [lexicWord]#skill#, so a [lexicWord]#skill# of 0 would still allow one die to be rolled.
====

Attacking someone, using magic, resisting the effect of a spell or from the elements, preparing a feast will all work in the same manner; all those are [lexicWord]#skills# based.

The reason I went with this dice system is the good tactile feedback you get from the dice-pool and how it gives you an impression of the ability of your [lexicWord]#character#.
You can feel in your hand, before you roll, the difference between a task you are good at and one you are mediocre.
You can feel the varying odds of success, in you favour when you roll 5d12, not so much if you can only roll 1d4.

Amongst the other things in the [lexicWord]#SdA system# that distinguish it from other rule set you will find:

* A dynamic and strategic combat system base of choice and trade-off

* Damage and [lexicWord]#injuries# with consequences

* A variety of weapon and armour type with implications beyond the cosmetic

* [lexicWord]#Characters# not defined by a class but by their lived experience

* Progression not based on levels but on what the [lexicWord]#characters# do and what [lexicWord]#skills# they use.

Most of those mechanics exist in other systems in one way or another, I recognize that, but I wanted to bring them all together in harmony, in a coherent and easy to learn manner.

'''

=== Rules or Guidelines

The goal of role-playing games usually is to collaboratively create a story where the [lexicWord]#player character# are the protagonists.
The [lexicWord]#players# and [lexicWord]#GM#, should work together towards this goal.
If the rules get in the way of the story, the [lexicWord]#GM# can decide to put them aside, tweak them, bend them.

At the start of a new campaign, feel free to have a discussion amongst your group and decide if some rules are going to be ignores or modified.
Those changes are referred to as "house rules" or "homebrew".
If you realize that those alterations are a detriment to the game, don't hesitate to take a moment to re-open the conversation with your group, preferably not mid-session.

Of course, every adjustment of the rules need to be approved by the [lexicWord]#GM#.
[lexicWord]#GMs# always have the last word when it comes to guidelines interpretation, adaptation or abolition.

There is a maxim that is often considered to apply to all [lexicWord]#RPGs#: the "rule zero", sometimes referred to as "the rule of cool".
This 0th rule suggest that, since [lexicWord]#RPGs# are entertainment, the group should do whatever is necessary to make the game as entertaining as possible.
If a [lexicWord]#player# or the [lexicWord]#GM# suggest something that is not strictly by the rules as written (RaW) but is truly awesome, just go with it.

Of course, if the "rule of cool" is invoked too frequently, it will lose it's impact.
Like in most things, it is a matter of balance.
The right amount of adherence to the RaW will vary from group to group.
You will, over time, find the style of play that is right for you, that you enjoy the most.

In reason of the flexibility of the rules, they could be seem more as guidelines.
This does not mean that they should be seen as mere suggestions; a great amount of thoughts and considerations has been put in the conception of this system to offer engaging experiences.

Remember that [lexicWord]#RPGs# are intended to be games; if you completely ignore the rules, you'll lose that aspect of the activity.

'''

=== Exposing my Biases

I tried to design the SdA system to allow different styles of play.
Some people prefer more fantastic games, some prefer more gritty one.
Some GM will run game of epic proportions where the characters need to save the world while other will present scenarii much more toned down.
There is no correct type of game.
The best option is the one your group of players enjoys the most.

Even though I tried to minimize my bias towards one specific type of play, some will still be apparent in the fundamental design of the system.
In a desire of transparency, I decided to be upfront about it and declare my biases right here, in the introduction of the book.
I hope you won't take this as meaning that if your preferences vary, WinterDawn won't be adapted for your style of play (and I hope even more that it is not the case).

When it comes to magic, I always preferred setting where magic is rare, strange and scary.
Only a few people can practice it, sometimes it has to be done underground, without the authorities or the non-initiated finding out.

As for the power level of the characters, I always enjoy starting out a game with characters who are barely more competent than the average person of the setting.
Slightly above average.
I truly enjoy experiencing the growth of a character until they become exceptional individuals.
I believe that what makes someone a hero is not their aptitudes, skills and abilities but the way they act in extraordinary situations.

I can see the appeal of epic game but I've always been more inclined towards more toned down scope, campaign where characters pursue more personal goals.
I like those characters to be mostly good but, to have them in very grey situations where there is no perfectly palatable solution.

I also enjoy more realistic game with deadly combats, where you have to think twice before resorting to violence.

I usually run combats with miniatures on a hexagonal grid with the characters facing towards a point (instead of an edge) so there are two hexes in front of the character two on their side (one on each) and two in their back.

Finally, I have to add, I always add a bias towards orcs and against elves.
I tried to keep all the race more or less balanced but, even though there are not necessarily more powerful, I find the orcs cooler than the rest.
I'm sure many people will disagree with me and that is perfect.
