= The SdA system: Engine of the Game
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2018-08-21
:root: ./
:description: This is the base mechanics of the game.
include::{root}Include.adoc[]

<<<

== Basic Mechanics

In order to add both objectivity and randomness to role-playing games, game mechanics are used to define what a [lexicWord]#character# can and can't do, how well-equipped they are to overcome different challenges and if they succeed or fail at whatever they are trying to accomplish.

'''

=== Attributes

Six [lexicWord]#attributes# define every [lexicWord]#character#.
Those are [lexicWord]#agility#, [lexicWord]#constitution#, [lexicWord]#strength#, [lexicWord]#erudition#, [lexicWord]#persona# and [lexicWord]#wisdom#.

[lexicWord]#Attributes# for a humanoid [lexicWord]#character# will usually vary between 4 and 12.
The highest the [lexicWord]#attribute's# score, the better.

* Scores below 4 are crippling.
* Scores of 5 or 4 are considered weak.
* An average attribute has a value of 6 or 7.
* Scores of 8 or 9 are relatively strong.
* Scores of 10 or 11 are viewed as exceptional.
* Scores of 12 are worthy of heroes.
* Scores of 20 or higher would be supernatural.

==== Agility

This [lexicWord]#attribute# represents the dexterity and nimbleness of the [lexicWord]#character#.
It covers fine motor skills, eye-hand coordination and balance.

==== Constitution

A [lexicWord]#character#'s [lexicWord]#constitution# represent not only his health but also their resistance to different types of punishment.

[lexicWord]#Constitution# also affect the rate at which a [lexicWord]#character# recover from injuries.

==== Strength

[lexicWord]#Strength# represents the physical power and explosiveness of a [lexicWord]#character#.

==== Erudition

[lexicWord]#Erudition# is the [lexicWord]#attribute# for formal learning, academic knowledge and book-smartness.

==== Persona

This [lexicWord]#attribute# represents the strength of personality and charisma of the [lexicWord]#character#.
[lexicWord]#Characters# with a high persona score tend to be very polarizing individuals and will leave a strong impression on the people they meet.

==== Wisdom

[lexicWord]#Wisdom# is the sagacity and common sense of the [lexicWord]#character#.
A down to earth, no non-sense, resourceful [lexicWord]#character# would be one with a high [lexicWord]#wisdom# score.

.Erudition and Wisdom
[NOTE]
====
If [lexicWord]#erudition# is related to being book-smart, [lexicWord]#wisdom# will cover the street-smart of a [lexicWord]#character#.
While [lexicWord]#erudition# is very theoretical, [lexicWord]#wisdom# is more on the practical side of things.
====

'''

=== Dice

{gameName} is played with [lexicWord]#polyhedral dice#.
6 types of dice are used: 4-sided, 6-sided, 8-sided, 10-sided, 12-sided and 20-sided.

Those dice are usually referred to by the letter “d” followed by the number of faces (d4, d6, d8, etc).
When a number is noted before the letter “d”, it represents the number of dice to be rolled.

.Example
[caption = ""]
====
“3d12” means three twelve-sided dice.
====

'''

=== Skills

A large array of different [lexicWord]#skills# covers what a [lexicWord]#character# can reasonably be expected to do.
Each of those [lexicWord]#skills# linked to one or two [lexicWord]#attributes#.
They are also grouped 4, 5 or 6 together in [lexicWord]#skill groups# (except for [lexicWord]#luck# being on its own).

When a rule refer to the [lexicWord]#rank# of a [lexicWord]#skill#, the [lexicWord]#rank# of the [lexicWord]#skill group# it is part of should always be added, unless specified otherwise.

.Example
[caption=""]
====
The [lexicWord]#rank# of [lexicWord]#folklore# always included the [lexicWord]#ranks# of its [lexicWord]#group#, [lexicWord]#knowledge#.
====

Each [lexicWord]#skill# is going to be described in the following chapter with some example of uses.

////
==== Skill Groups

Some [lexicWord]#skills# are gathered together under a [lexicWord]#skill group#.
Those [lexicWord]#skill groups# will have a [lexicWord]#rank# that should be added to every [lexicWord]#skill# underneath when making a [lexicWord]#roll# and when calculating the cost of increasing the [lexicWord]#skill's rank#.

.Example
[caption = ""]
====
A [lexicWord]#character# needs to make a [lexicWord]#sheltering# test to build camp for the night.
[lexicWord]#Sheltering# is in the [lexicWord]#Survival group#; those two scores will be added together to determine the size of the [lexicWord]#dice-pool#.
====
////
'''

=== Skill Test

Whenever a [lexicWord]#player# desires to attempt an action which could either succeed or fail, the [lexicWord]#GM# may ask for a [lexicWord]#skill test#.

The number of dice to be rolled for a [lexicWord]#skill test# is equal to 1 + the [lexicWord]#ranks# of the [lexicWord]#skill# being tested.
The type of dice is determined by the [lexicWord]#attribute# governing the [lexicWord]#skill# being tested; the dice used must have no more face than the value of the [lexicWord]#attribute#.
If the [lexicWord]#skill# is governed by more than one [lexicWord]#attribute#, the [lexicWord]#player# can usually choose the one to use.
Some circumstances will force the use of one [lexicWord]#attribute# over an other.

The resulting combination of the number and type of dice is referred to as a [lexicWord]#dice-pool#.

.Example
[caption = ""]
====
A [lexicWord]#skill# with a rank of 2 in a [lexicWord]#skill group# with a rank of 1 will allow the [lexicWord]#player# to roll 4 dice (2 + 1  + 1).
If this [lexicWord]#skill# is governed by an [lexicWord]#attribute# with a value of 7, the [lexicWord]#player# can roll 6 sided dice.
His [lexicWord]#dice-pool# for this test would then be of four six-sided dice, abbreviated as 4d6.
====

Tests made with an [lexicWord]#attribute# lower than four will be discussed below.

A test can involve more than one [lexicWord]#roll# and/or more than one [lexicWord]#dice-pool#.
The different types of test will be discussed later in this chapter.

A [lexicWord]#skill test# should only be asked for if the success or failure of an action will impact the narrative outcome.

.Dice-Pools and Rolls
[NOTE]
====
A [lexicWord]#dice-pool# represents the number and type of dice available to a [lexicWord]#player# for his [lexicWord]#character# to perform a certain task or action.

A [lexicWord]#roll# is the actual dice used to perform the task or action.

In most cases a [lexicWord]#dice-pool# and a [lexicWord]#roll# will be the same, but a [lexicWord]#player# can decide to roll fewer dice than their [lexicWord]#dice-pool# would allow.
The reasons and circumstances a [lexicWord]#player# would choose not to [lexicWord]#roll# their full [lexicWord]#dice-pool# will be covered later in this book.
====

'''

=== Success and Failure

To succeed on a [lexicWord]#skill test#, a number of [lexicWord]#measure of success (MoS)# equal or superior to a [lexicWord]#difficulty level# must be obtained.

Each die showing a 4 or more gives one or more [lexicWord]#MoSes#.

.MoS (Measure of Success) Per Die

* Every dice showing 4 to 7, inclusively, give 1 [lexicWord]#MoS#.
* Dice showing 8 to 11 grant 2 [lexicWord]#MoSes#.
* Dice showing 12 to 15 count for 3 [lexicWord]#MoSes#.
* Dice showing 16 to 19 award 4 [lexicWord]#MoSes#.
* Dice showing 20 deliver 5 [lexicWord]#MoSes#.

'''

=== Difficulty Level

A wide array of tasks will call for a variety of [lexicWord]#difficulty level#.
Some will be mundane, some will be near impossible.

The [lexicWord]#GM# will determine the number of [lexicWord]#MoSes# required to succeed at the task.

* *Easy tasks* need 1 [lexicWord]#MoS# to be accomplished.
+
Such tasks have 50% chance of success when attempted by an average [lexicWord]#character#, untrained in the [lexicWord]#skill# being used.

* *Moderate tasks* need 2 or 3 [lexicWord]#MoSes# to be accomplished.
+
An average [lexicWord]#character# need to be at least initiated in the [lexicWord]#skill# tested to have a chance at succeeding.

* *Difficult tasks* need 4 or 5 [lexicWord]#MoSes# to be accomplished.
+
Average [lexicWord]#chracters# without proper experience in the [lexicWord]#skill# being tested cannot expect to overcome such challenge.

* *Very difficult* tasks need 6 or 7 [lexicWord]#MoSes# to be accomplished.
+
Even a [lexicWord]#character# highly trained in the [lexicWord]#skill# being tested can be expected to fail at such tasks most of the time.

* *Near impossible* tasks need 8 or 9 [lexicWord]#MoSes# to be accomplished.
+
A [lexicWord]#character# accomplishing such a feat in front of an audience will leave them in awe.

* *Legendary tasks* need 10 or more [lexicWord]#MoSes# to be accomplished.
+
Witnesses of such accomplishments will have a hard time finding people to believe their recounting of the event.

The [lexicWord]#difficulty level# is either determined by the [lexicWord]#GM#, by a [lexicWord]#roll# made by an opponent or by different environmental factors.

Those numbers are for simple tasks which can be done in one action, in a short amount of time.
More complex enterprises that can be worked on for a prolonged amount of time can have much higher [lexicWord]#difficulty level#.
The [lexicWord]#GM# can allow a [lexicWord]#player# multiple test to achieve these kinds of undertakings.

'''

=== Hits

[lexicWord]#MoSes# exceeding the [lexicWord]#difficulty level# are called [lexicWord]#hits#.

.Example
[caption = ""]
====
The [lexicWord]#GM# ask a [lexicWord]#player# a test.
He determines the task is difficult and, therefore, the [lexicWord]#difficulty level# should be 3.
The [lexicWord]#chatacter# is quite good at the task, has a good [lexicWord]#dice-pool# and manage to roll 5 [lexicWord]#MoSes#.
This result in a success with 2 [lexicWord]#hits#.
====

Many [lexicWord]#skills#, [lexicWord]#spells# and other abilities have varying degree of effectiveness depending on the number of [lexicWord]#hits# obtained on a [lexicWord]#roll#.

'''

include::Types_of_Test.adoc[leveloffset=+2]

'''

=== Bonus and Malus

[lexicWord]#Dice-pools# and [lexicWord]#rolls# can be modified by [lexicWord]#bonuses# and [lexicWord]#maluses# based on the situations the [lexicWord]#characters# find themselves in.

[lexicWord]#Bonuses# grant additional dice to a [lexicWord]#dice-pool#.
If a [lexicWord]#bonuses# is applied to a [lexicWord]#rolling test#, it will benefit every [lexicWord]#rolls#, until the situation changes.

.Example
[caption = ""]
====
A [lexicWord]#character# is climbing a large tree.
He is using a specialized spikes and harness which grant him 1 die [lexicWord]#bonus#.
Climbing this tree can take multiple rolls; the equipment will grant the [lexicWord]#bonus# to each one.
====

[lexicWord]#Maluses# remove [lexicWord]#MoSes# from the [lexicWord]#roll#.
If a [lexicWord]#malus# affects a [lexicWord]#rolling test#, it will be applied to every [lexicWord]#roll#, unless the situation changes between [lexicWord]#rolls#.

.Example
[caption = ""]
====
A [lexicWord]#character# is looking for tracks in the woods at night without a proper light source.
The [lexicWord]#tracking rolls# will receive a -2 [lexicWord]#MoSes malus#.
====

If a [lexicWord]#character# involved in an [lexicWord]#opposed test# suffer [lexicWord]#maluses# that would bring his total [lexicWord]#MoSes# below 0, his opponent can add a number of [lexicWord]#bonus# dice equal to the remainder of the [lexicWord]#malus# to their roll.

.Example
[caption = ""]
====
An assassin sneaked up on her target to stab him in the back.
Being [lexicWord]#reared#, the mark would suffer a [lexicWord]#malus# of 2 [lexicWord]#MoSes# on his defence.
Since he is unaware of the attacker, he is not allowed a roll and the assassin will add 2 dice to her [lexicWord]#dice-pool#.
====

'''

=== Flawless Success

For a roll to be considered a [lexicWord]#flawless success# three conditions must be met:

. The full [lexicWord]#dice-pool# must be rolled and
. Every dice rolled must grant at least one [lexicWord]#MoS# and
. The task attempted must be successful.

[lexicWord]#Flawless successes# can be used to either regain a number of [lexicWord]#spirit points# equal to the number of [lexicWord]#MoSes# obtained or gain one [lexicWord]#experience point# in the [lexicWord]#skill# tested.

=== Complete Failure

If no dice in a [lexicWord]#roll# grant any [lexicWord]#MoS#, it is considered a [lexicWord]#complete failure#.

In case of a [lexicWord]#complete failure#, the player must do an [lexicWord]#ego test# as a [lexicWord]#free roll#.
The [lexicWord]#difficulty level# of the [lexicWord]#ego test# is equal to the [lexicWord]#rank# of the [lexicWord]#skill# which caused the [lexicWord]#complete Failure#.

If the [lexicWord]#ego test# is successful, the [lexicWord]#character# gains one [lexicWord]#experience point# in the [lexicWord]#skill# which caused the [lexicWord]#complete failure#.
If the [lexicWord]#ego test# is failed, the [lexciWord]#character# loses a number of [lexicWord]#spirit points# equal to the rank of the [lexicWord]#skill# that caused the [lexicWord]#complete failure#.

If a [lexicWord]#character# obtains a [lexicWord]#complete failure# on a [lexicWord]#skill# with no [lexicWord]#ranks#, the [lexicWord]#ego test# cannot fail.
It is still worth rolling the [lexicWord]#ego test# as it can be subject to [lexicWord]#flawless success# and [lexicWord]#complete failure#.

.Example
[caption = ""]
====
During a fight, a [lexicWord]#character# wants to flip a table to take cover behind it.
The [lexicWord]#GM# announces a single [lexicWord]#MoS# will be necessary.
The [lexicWord]#character# has an [lexicWord]#athelticism# score of 2, allowing 3 dice to roll.
The [lexicWord]#player# decides to only use one die, in order to keep more dice available for defence.
The [lexicWord]#roll# grants no [lexicWord]#MoSes#, forcing the [lexicWord]#player# to make an [lexicWord]#ego test#.
The [lexicWord]#difficulty level# is 2, the [lexicWord]#athleticism# level of the [lexicWord]#character#.
If the [lexicWord]#ego test# is successful, 1 [lexicWord]#experience point# will be gained in the [lexicWord]#athleticism skill#.
If it is failed, 2 [lexicWord]#spirit points# will be lost.
====

'''

=== Test with [lexicWord]#Attributes# Below Four

For every [lexicWord]#rank# the [lexicWord]#attribute# is below 4, the [lexicWord]#player# must add to his [lexicWord]#dice-pool# 1 [lexicWord]#bonus# die, but must subtract a 1 [lexicWord]#MoS# [lexicWord]#malus# to his result.

.Example
[caption = ""]
====
A [lexicWord]#character# with an [lexicWord]#attribute# of 2 will have to add 2 dice to [lexicWord]#dice-pools# based on this [lexicWord]#attribute#.
2 [lexicWord]#MoSes# will be subtracted from the result of the roll.

If the [lexicWord]#skill# tested has no ranks, the [lexicWord]#dice-pool# will be of 3 dice.
If the roll result in 2 [lexicWord]#MoSes#, after the [lexicWord]#malus# is applied, the result will be 0.
====

'''

include::Spirit.adoc[leveloffset=+2]

'''

include::Improving_Skills_and_Attributes.adoc[leveloffset=+2]

'''

include::Virtues.adoc[leveloffset=+2]

'''

include::Tempo.adoc[leveloffset=+2]

'''

<<<

include::SideBarPages/Basic_Rules.adoc[leveloffset=+2,lines=2..-1]

////
<<<

include::SideBarPages/What_Is_A_Character_Made_Of.adoc[leveloffset=+2,lines=2..-1]
////
<<<

include::Skills.adoc[leveloffset=+1]

<<<

include::Combat.adoc[leveloffset=+1]

<<<
