= The SdA system: Engine of the Game
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2017-12-09
:root: ./
:description: This is the base mechanics of the game.
include::{root}Include.adoc[]

<<<

== Basic Mechanics

In order to add both objectivity and randomness to role-playing games, game mechanics are used to define what a [lexicWord]#character# can and can't do, how well-equipped they are to overcome different challenges and if they succeed or fail at whatever they are trying to accomplish.

'''

=== Attributes

Six [lexicWord]#attributes# define every [lexicWord]#character#.
Those are [lexicWord]#agility#, [lexicWord]#constitution#, [lexicWord]#strength#, [lexicWord]#erudition#, [lexicWord]#persona# and [lexicWord]#wisdom#.

[lexicWord]#Attributes# for a humanoid [lexicWord]#character# will usually vary between 4 and 12.
The highest the [lexicWord]#attribute's# score, the better.

* Scores below 4 are crippling.
* Scores of 5 or 4 are considered weak.
* An average attribute has a value of 6 or 7.
* Scores of 8 or 9 are relatively strong.
* Scores of 10 or 11 are viewed as exceptional.
* Scores of 12 are worthy of heroes.
* Scores of 20 or higher would be supernatural.

==== Agility

This [lexicWord]#attribute# represents the dexterity and nimbleness of the [lexicWord]#character#.
It covers fine motor skills, eye-hand coordination and balance.

==== Constitution

A [lexicWord]#character#'s [lexicWord]#constitution# represent not only his health but also their resistance to different types of punishment.

[lexicWord]#Constitution# also affect the rate at which a [lexicWord]#character# recover from injuries.

==== Strength

[lexicWord]#Strength# represents the physical power and explosiveness of a [lexicWord]#character#.

==== Erudition

[lexicWord]#Erudition# is the [lexicWord]#attribute# for formal learning, academic knowledge and book-smartness.

==== Persona

This [lexicWord]#attribute# represents the strength of personality and charisma of the [lexicWord]#character#.
[lexicWord]#Characters# with a high persona score tend to be very polarizing individuals and will leave a strong impression on the people they meet.

==== Wisdom

[lexicWord]#Wisdom# is the sagacity and common sense of the [lexicWord]#character#.
A down to earth, no non-sense, resourceful [lexicWord]#character# would be one with a high [lexicWord]#wisdom# score.

.Erudition and Wisdom
[NOTE]
====
If [lexicWord]#erudition# is related to being book-smart, [lexicWord]#wisdom# will cover the street-smart of a [lexicWord]#character#.
While [lexicWord]#erudition# is very theoretical, [lexicWord]#wisdom# is more on the practical side of things.
====

'''

=== Dice

{gameName} is played with [lexicWord]#polyhedral dice#.
6 types of dice are used: 4-sided, 6-sided, 8-sided, 10-sided, 12-sided and 20-sided.

Those dice are usually referred to by the letter “d” followed by the number of faces (d4, d6, d8, etc).
When a number is noted before the letter “d”, it represents the number of dice to be rolled.

.Example
[caption = ""]
====
“3d12” means three twelve-sided dice.
====

'''

=== Skills

A large array of different [lexicWord]#skills# covers what a [lexicWord]#character# can reasonably be expected to do.
Each of those [lexicWord]#skills# is linked to one or two [lexicWord]#attributes#.

Each [lexicWord]#skill# is going to be described in the following chapter.

==== Skill specialities

Some [lexicWord]#skills# are subdivided into five [lexicWord]#specialities#.

Those [lexicWord]#skills# should not be tested directly but tests should be made with one of their [lexicWord]#speciality#.

The [lexicWord]#ranks# of the parent [lexicWord]#skill# should always be added to the [lexicWord]#speciality# when this last one is being tested.

The [lexicWord]#ranks# of the [lexicWord]#skill# and of the [lexicWord]#speciality# being tested should always be added together.

.Example
[caption = ""]
====
A [lexicWord]#character# needs to make a [lexicWord]#sheltering# test to build camp for the night.
[lexicWord]#Sheltering# is a [lexicWord]#Survival speciality#; those two scores will be added together to determine the size of the [lexicWord]#dice-pool#.
====

'''

=== Skill Test

Whenever a [lexicWord]#player# desires to attempt an action which could either succeed or fail, the [lexicWord]#GM# may ask for a [lexicWord]#skill test#.

The number of dice to be rolled for a [lexicWord]#skill test# is equal to 1 + the [lexicWord]#ranks# of the [lexicWord]#skill# being tested.
The type of dice is determined by the [lexicWord]#attribute[lexicWord]# governing the [lexicWord]#skill# being tested; the dice used must have no more face than the value of the [lexicWord]#attribute#.
If the [lexicWord]#skill# is governed by more than one [lexicWord]#attribute#, the [lexicWord]#player# can usually choose the one to use.
Some circumstances will force the use of one [lexicWord]#attribute# over an other.

The resulting combination of the number and type of dice is referred to as a [lexicWord]#dice-pool#.

.Example
[caption = ""]
====
A [lexicWord]#skill# with a rank of 3 will allow the [lexicWord]#player# to roll 4 dice.
If this [lexicWord]#skill# is governed by an [lexicWord]#attribute# with a value of 7, the [lexicWord]#player# can roll 6 sided dice.
His [lexicWord]#dice-pool# for this test would then be of four six-sided dice, abbreviated as 4d6.
====

Even if a [lexicWord]#character# has no rank in a [lexicWord]#skill#, the [lexicWord]#player# can still roll 1 die, granted by the [lexicWord]#attribute#.

If the [lexicWord]#attribute# is lowered than 4, the [lexicWord]#dice-pools# will still be composed of d4s, but the [lexicWord]#character# will have to spend 1 [lexicWord]#spirit point# per rank below 4, per die rolled.
If the test is [lexicWord]#opposed#, the [lexicWord]#character# will have [lexicWord]#disadvantage#.

.Example
[caption = ""]
====
If a [lexicWord]#character# has an [lexicWord]#attribute# of 2 but a [lexicWord]#skill# of 1, the [lexicWord]#player# has access to a [lexicWord]#dice-pool# of 2d4 but will need to spend 4 [lexicWord]#spirit points# ((4-2)*2 = 4).
====

A test can involve more than one [lexicWord]#roll# and/or more than one [lexicWord]#dice-pool#.
The different types of test will be discussed later in this chapter.

A [lexicWord]#skill test# should only be asked for if the success or failure of an action will impact the narrative outcome.

.Dice-Pools and Rolls
[NOTE]
====
A [lexicWord]#dice-pool# represents the number and type of dice available to a [lexicWord]#player# for his [lexicWord]#character# to perform a certain task or action.

A [lexicWord]#roll# is the actual dice used to perform the task or action.

In most cases a [lexicWord]#dice-pool# and a [lexicWord]#roll# will be the same, but a [lexicWord]#player# can decide to roll fewer dice than their [lexicWord]#dice-pool# would allow.
The reasons and circumstances a [lexicWord]#player# would choose not to [lexicWord]#roll# their full [lexicWord]#dice-pool# will be covered later in this book.
====

'''

=== Success and Failure

To succeed on a [lexicWord]#skill test#, a number of [lexicWord]#measure of success (MoS)# equal or superior to a [lexicWord]#difficulty level# must be obtained.

Each die showing a 4 or more gives one or more [lexicWord]#MoSes#.

.MoS (Measure of Success) Per Die

* Every dice showing 4 to 7, inclusively, give 1 [lexicWord]#MoS#.
* Dice showing 8 to 11 grant 2 [lexicWord]#MoSes#.
* Dice showing 12 to 15 count for 3 [lexicWord]#MoSes#.
* Dice showing 16 to 19 award 4 [lexicWord]#MoSes#.
* Dice showing 20 deliver 5 [lexicWord]#MoSes#.

'''

=== Difficulty Level

A wide array of tasks will call for a variety of [lexicWord]#difficulty level#.
Some will be mundane, some will be near impossible.

The [lexicWord]#GM# will determine the number of [lexicWord]#MoSes# required to succeed at the task.

* *Easy tasks* need 1 [lexicWord]#MoS# to be accomplished.
+
Such tasks have 50% chance of success when attempted by an average [lexicWord]#character#, untrained in the [lexicWord]#skill# being used.

* *Moderate tasks* need 2 or 3 [lexicWord]#MoSes# to be accomplished.
+
An average [lexicWord]#character# need to be at least initiated in the [lexicWord]#skill# tested to have a chance at succeeding.

* *Difficult tasks* need 4 or 5 [lexicWord]#MoSes# to be accomplished.
+
Average [lexicWord]#chracters# without proper experience in the [lexicWord]#skill# being tested cannot expect to overcome such challenge.

* *Very difficult* tasks need 6 or 7 [lexicWord]#MoSes# to be accomplished.
+
Even a [lexicWord]#character# highly trained in the [lexicWord]#skill# being tested can be expected to fail at such tasks most of the time.

* *Near impossible* tasks need 8 or 9 [lexicWord]#MoSes# to be accomplished.
+
A [lexicWord]#character# accomplishing such a feat in front of an audience will leave them in awe.

* *Legendary tasks* need 10 or more [lexicWord]#MoSes# to be accomplished.
+
Witnesses of such accomplishments will have a hard time finding people to believe their recounting of the event.

The [lexicWord]#difficulty level# is either determined by the [lexicWord]#GM#, by a [lexicWord]#roll# made by an opponent or by different environmental factors.

Those numbers are for simple tasks which can be done in one action, in a short amount of time.
More complex enterprises that can be worked on for a prolonged amount of time can have much higher [lexicWord]#difficulty level#.
The [lexicWord]#GM# can allow a [lexicWord]#player# multiple test to achieve these kinds of undertakings.

'''

=== Hits

[lexicWord]#MoSes# exceeding the [lexicWord]#difficulty level# are called [lexicWord]#hits#.

.Example
[caption = ""]
====
The [lexicWord]#GM# ask a [lexicWord]#player# a test.
He determines the task is difficult and, therefore, the [lexicWord]#difficulty level# should be 3.
The [lexicWord]#chatacter# is quite good at the task, has a good [lexicWord]#dice-pool# and manage to roll 5 [lexicWord]#MoSes#.
This result in a success with 2 [lexicWord]#hits#.
====

Many [lexicWord]#skills#, [lexicWord]#spells# and other abilities have varying degree of effectiveness depending on the number of [lexicWord]#hits# obtained on a [lexicWord]#roll#.

'''

include::Types_of_Test.adoc[leveloffset=+2]

'''

=== Bonus and Malus

[lexicWord]#Characters# can gain bonus or suffer malus depending on the situation they have to perform a task.

Bonuses come in two form: Additional [lexicWord]#MoSes# or additional dice to a [lexicWord]#dice-pool#.

Bonuses to [lexicWord]#MoSes# are noted by a simple +1 [lexicWord]#MoS#.
Bonuses to a [lexicWord]#dice-pool# are noted as +1d.

To benefit from bonus [lexicWord]#MoSes# a player must have dice leftover in their [lexicWord]#dice-pool#.

Bonuses giving extra dice can be used even with a depleted [lexicWord]#dice-pool#.

Malus removes [lexicWord]#MoSes# from a roll.  They are noted as -1 [lexicWord]#MoS#.

'''

=== Resounding Success

For a roll to be considered a [lexicWord]#resounding success# two conditions must be met:

. The task attempted must be successful and
. The number of [lexicWord]#MoSes# obtained on the roll (before adding any bonus [lexicWord]#MoSes#) must be equal or greater to the number of dice granted by the [lexicWord]#dice-pool# for this task.

[lexicWord]#Resounding success# can be used to regain [lexicWord]#spirit# or gain [lexicWord]#experience#.
Details are given further in this chapter.

=== Complete Failure

A roll ending up with [lexicWord]#Losses# (before any malus has been applied) is a [lexicWord]#complete failure# of the [lexicWord]#character#.

A [lexicWord]#complete failure# can cause a lost of [lexicWord]#spirit# or a gain of [lexicWord]#experience#.
While outside of combat, if a player rolls a [lexicWord]#complete failure# they must make a [lexicWord]#Confidence & ego# test with a [lexicWord]#difficulty level# equals to 1 + the number of [lexicWord]#losses#.
If this roll is successful, the [lexicWord]#player# can put an [lexicWord]#experience points# in the failed [lexicWord]#skill#.
If the roll is unsuccessful, the [lexicWord]#character# loses 1 [lexicWord]#spirit point# per [lexicWord]#ranks# in the failed [lexicWord]#skill#.

[lexicWord]#Complete failures# can also imply a complication.
Some examples are given in the description of certain tasks.

In case of a [lexicWord]#complete failure# on an [lexicWord]#opposed test#, the [lexicWord]#losses# are generally added to the roll of the opposing [lexicWord]#character#.

include::Spirit.adoc[leveloffset=+2]

include::Improving_Skills_and_Attributes.adoc[leveloffset=+2]

.{sidebarTitle}What is a character made off?
[sidebar]
****
* Name: What the [lexicWord]#character# is known as.
* [lexicWord]#Race#: The racial make up of the [lexicWord]#character#.
Chose between High-Man, Highland Half-Man, Lowland Half-Man, Orc, Goblin, Hobgoblin, Elf, Faun and Troll.

* Description: The gender, age, height, weight and other details of the physical appearance of the [lexicWord]#character#.

* [lexicWord]#Attributes#: [lexicWord]#Agility#, [lexicWord]#power#, [lexicWord]#constitution#, [lexicWord]#erudition#, [lexicWord]#sagacity# and [lexicWord]#persona#.
Those represent the base disposition of the [lexicWord]#character# in each of these domains.

* [lexicWord]#Skills#: The list of [lexicWord]#skills# the [lexicWord]#character# knows or has [lexicWord]#experience# in.

* [lexicWord]#Experience spent#: The amount of [lexicWord]#experience points# the [lexicWord]#player# spent to purchase [lexicWord]#skills#, [lexicWord]#attributes# or [lexicWord]#traits#

* [lexicWord]#Traits#: Special features making the [lexicWord]#character# unique.
Some are gained on [lexicWord]#character creation# while others can be gained while playing.

* [lexicWord]#Spirit#: A mix between moral and stamina, this is what keep the [lexicWord]#character# going.

* Health: The number and type of [lexicWord]#injuries# the [lexicWord]#character# is currently suffering from as well as the different effects caused by those [lexicWord]#injuries#.

* Arsenal: The list of weapons the [lexicWord]#character# currently has on them ready to use.

* Armour: The current armour worn by the [lexicWord]#character# and the tally of the total passive defence offered by this one.

* Equipment: All the different piece of equipment the [lexicWord]#character# carries on their person.

* Wealth: The money carried by the [lexicWord]#character# by denomination.
Three types of coins exist: Copper, Silver and Gold.

* [lexicWord]#Encumbrance#: A mix of weight and inconvenience of the equipment carried by the [lexicWord]#character# including the weapons, armour, money, food and water.

* [lexicWord]#Morality#: Where the [lexicWord]#character# falls on the good and evil axis, their honour and faith.

* [lexicWord]#Vice & Virtues#: Represent the inclination of the character towards different [lexicWord]#vices and virtues#.
Each virtue lies between two vice.
The five virtues are [lexicWord]#courage#, [lexicWord]#temperance#, [lexicWord]#generosity#, [lexicWord]#magnanimity# and [lexicWord]#friendliness#.
****

<<<

include::Skills.adoc[leveloffset=+1]

<<<

include::Combat.adoc[leveloffset=+1]

<<<
