= Virtues
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2017-12-09
:root: ./
:description: This is the description of the virtues mechanics.
include::Include.adoc[]

[lexicWord]#Virtues# help define a [lexicWord]#character's# personality and support consistency in his behaviour.
They can also represent a way to gauge the evolution of the [lexicWord]#character#, or serve as a goal to attain.

There are seven [lexicWord]#virtues# defining a [lexicWord]#character#, each existing on a spectrum.
One end of those spectra represents a lack of the [lexicWord]#virtue#, while the other stands for an excess of it.
An argument can be made for balance, but different people and different cultures will consider different position on those spectra has being the ideal ones.
This is why the extremes are presented with a pair of terms, one being more positive, the other more negative.


.Vices and Virtues
[cols="3*^.^",options="header", caption ="", width = 50%, align="center"]
|===
| Virtues | Lack of | Excess of
| Bravery | Craven / Prudent | Reckless / Daring
// | Etiquette | Rude / Frank | Tamed / Polite
| Faith | Iconoclast / Skeptic | Zealot / Devotee
// | Friendliness | Aloof / Reserved | Fawning / Caring
| Integrity | Devious / Cunning | Intransigent / Honourable
| Pride | Meek / Humble | Vain / Dignified
| Temperance | Debauched / Epicurean | Insensitive / Disciplined
|===

Each spectrum is divided in 6 steps; the [lexicWord]#character# will be place on one of those step for each [lexicWord]#virtue#.

Those steps can be described as:

* The complete lack of the [lexicWord]#virtue#
* Leaning towards the lack of the [lexicWord]#virtue#
* The two median step represent the balance between the two extremes
* Leaning towards the excess of the [lexicWord]#virtue#
* The complete excess of the [lexicWord]#virtue#

If a [lexicWord]#character# is in a situation where they have to act in accordance with one of the extreme end of a [lexicWord]#virtue#, they can call upon this virtue to assist them in their task.
The [lexicWord]#player# have to state their case to the [lexicWord]#GM# and explain why the way their [lexicWord]#character# is acting express the [lexicWord]#virtue# called upon.
The [lexicWord]#GM# has the final word as to if the [lexicWord]#virtue# is appropriate or not to support the action.
If he authorizes it, the [lexicWord]#player# will do a [lexicWord]#virtue roll#.
The type of die to be used for this roll depends on where on the spectrum of the [lexicWord]#virtue# the [lexicWord]#character# is; the closer he is to the exhibited extreme, the bigger the die used.

.Die types for [lexicWord]#Virtue# tests
[cols="^.^3, ^.^2, ^.^2", caption ="", width = 50%, align="center"]
|===
.2+h| Placement on the spectrum 2+h| Enacting
h| a lack of the virtue h| an excess of the virtue
| Complete lack | d12 | d4
| Leaning towards a lack | d10 | d6
| Balanced | d8 |d8
| Leaning towards an excess | d6 | d10
| Complete excess | d4 | d12
|===

[lexicWord]#Virtues test's dice-pool# are composed of one die by default.
[lexicWord]#Players# can add dice by spending a number of [lexicWord]#spirit points# equals to the current number of dice in their [lexicWord]#dice-pool#, as per any other rolls, but are not limited in the number of dice that can be bought in this way.

.Example
[caption =  ""]
====
A [lexicWord]#character# is facing an enemy of a similar power level, but she decides nonetheless to run rather than confront him.
The [lexicWord]#player# asks the [lexicWord]#GM# to call upon her [lexicWord]#character's# [lexicWord]#prudence#.
The [lexicWord]#GM# agrees that running from this enemy is a cowardly thing to do, so he allows the roll.
The [lexicWord]#character# is leaning towards [lexicWord]#craven / prudent# so the [lexicWord]#dice-pool# will be of 1d10.
An additional die could be added to the [lexicWord]#dice-pool# by spending 1 [lexicWord]#spirit point#.
Alternatively, two dice could be added by spending 3 [lexicWord]#spirit points# (1 + 2), or three dice for 6 [lexicWord]#spirit points# (1 + 2 + 3), etc.
====

For every [lexicWord]#MoSes# obtained on the [lexicWord]#virtue roll#, the [lexicWord]#player# can add 1 die to every [lexicWord]#dice-pool# that supports the [lexicWord]#character# acting accordingly to the end of the spectrum of the virtue called upon.
On the other hand, an equivalent [lexicWord]#malus# will be applied to every roll going against the [lexicWord]#virtue# called upon.

Those [lexicWord]#bonuses# and [lexicWord]#maluses# will last until the scene end.

.Example
[caption = ""]
====
The [lexicWord]#player# makes her [lexicWord]#craven / prudent# roll.
She decided to add two dice to her [lexicWord]#dice-pool#, bringing it to 3d10, and obtained 4 [lexicWord]#MoSes#.
This will allow her to add 4 dice to every [lexicWord]#dice-pool# to run away, hide or any other activity with the objective of avoiding the conflict (at the discretion of the [lexicWord]#GM#).

If for some reason, inside the same scene, the [lexicWord]#character# has to change strategy, face the enemy and act bravely, every roll supporting this new attitude will have 4 [lexicWord]#MoSes# subtracted from its result.
====

At the end of the scene, if the [lexicWord]#character# achieved his goal in a way supporting the end of the spectrum called upon, he will regained a number of [lexicWord]#spirit points# equal to the size of the dice rolled for the [lexicWord]#virtue roll# and the [lexicWord]#virtue# is moved one step towards the extreme impersonated.
If this is not judged to be the case, the [lexicWord]#virtue# of the [lexicWord]#character# will be moved towards the opposite extreme of what has been called upon.
He will also lose a number of [lexicWord]#spirit points# equal to the size of the dice used for the [lexicWord]#virtue roll#.

.Example
[caption = ""]
====
If our earlier [lexicWord]#character# manages to avoid the combat by running away or hiding, at the end of the scene, she will regain 10 [lexicWord]#spirit points# and her [lexicWord]#bravery# will be move one step toward [lexicWord]#craven / prudent#, birnging it to the complete lack of the [lexicWord]#virtue#.

If the scene is resolved in a different manner, if there is a confrontation or if it conclude at the disadvantage of the [lexicWord]#character#, this last one will lose 10 [lexicWord]#spirit points# and her [lexicWord]#virtue# will be moved one step towards [lexicWord]#reckless / daring#, bringing her to [lexicWord]#balanced#.
====

Calling upon a [lexicWord]#virtue# can grant a powerful advantage, but committing to one extreme interpretation of a [lexicWord]#virtue# is also inherently risky.

== Bravery

[lexicWord]#Bravery# represent the way a [lexicWord]#character# will react in face of danger.


=== Craven / Prudent
