= Virtues
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2018-08-20
:root: ./
:description: This is the description of the virtues mechanics.
include::Include.adoc[]

[lexicWord]#Virtues# help define a [lexicWord]#character's# personality and support consistency in his behaviour.
They can also represent a way to gauge the evolution of the [lexicWord]#character#, or serve as a goal to attain.

There are seven [lexicWord]#virtues# defining a [lexicWord]#character#, each existing on a spectrum.
One end of those spectra represents a lack of the [lexicWord]#virtue#, while the other stands for an excess of it.
An argument can be made for balance, but different people and different cultures will consider different position on those spectra has being the ideal ones.
This is why the extremes are presented with a pair of terms, one being more positive, the other more negative.


.Vices and Virtues
[cols="3*^.^",options="header", caption ="", width = 50%, align="center"]
|===
| Virtues | Lack of | Excess of
| Courage | Craven / Prudent | Daring / Reckless
// | Etiquette | Rude / Frank | Tamed / Polite
| Faith | Iconoclast / Skeptic | Devout / Zealot
// | Friendliness | Aloof / Reserved | Fawning / Caring
| Honesty | Devious / Cunning | Frank / Pedantic
| Pride | Meek / Humble | Dignified / Vain
| Temperance | Debauched / Epicurean | Disciplined / Insensitive
|===

////

//I might want to rewrite the virtue section to replace the two tables by this one:

.Vices and Virtues
[cols="6*^.^",options="header", caption ="", width = 90%, align="center"]
|===
| d12 / d4 | d10 / d6 | d8 / d8 | d8 / d8 | d6 / d10 | d4 / d12
| Craven | Prudent 2+| Courageous | Daring | Reckless
| Iconoclast | Skeptic 2+| Faithful | Devout | Zealot
| Devious | Cunning 2+| Honest | Frank | Pedantic
| Meek | Humble 2+| Proud | Dignified | Vain
| Debauched | Epicurean 2+| Mild | Disciplined | Insensitive
|===
////

Each spectrum is divided in 6 steps; the [lexicWord]#character# will be place on one of those step for each [lexicWord]#virtue#.

Those steps can be described as:

* The complete lack of the [lexicWord]#virtue#
* Leaning towards the lack of the [lexicWord]#virtue#
* The two median step represent the balance between the two extremes
* Leaning towards the excess of the [lexicWord]#virtue#
* The complete excess of the [lexicWord]#virtue#

If a [lexicWord]#character# is in a situation where they have to act in accordance with one of the extreme end of a [lexicWord]#virtue#, they can call upon this virtue to assist them in their task.
The [lexicWord]#player# have to state their case to the [lexicWord]#GM# and explain why the way their [lexicWord]#character# is acting express the [lexicWord]#virtue# called upon.
The [lexicWord]#GM# has the final word as to if the [lexicWord]#virtue# is appropriate or not to support the action.
If he authorizes it, the [lexicWord]#player# will do a [lexicWord]#virtue roll#.
The type of die to be used for this roll depends on where on the spectrum of the [lexicWord]#virtue# the [lexicWord]#character# is; the closer he is to the exhibited extreme, the bigger the die used.

.Die types for [lexicWord]#Virtue# tests
[cols="^.^3, ^.^2, ^.^2", caption ="", width = 50%, align="center"]
|===
.2+h| Placement on the spectrum 2+h| Enacting
h| a lack of the virtue h| an excess of the virtue
| Complete lack | d12 | d4
| Leaning towards a lack | d10 | d6
| Balanced | d8 |d8
| Leaning towards an excess | d6 | d10
| Complete excess | d4 | d12
|===

[lexicWord]#Virtues test's dice-pool# are composed of one die by default.
[lexicWord]#Players# can add dice by spending a number of [lexicWord]#spirit points# equals to the current number of dice in their [lexicWord]#dice-pool#, as per any other rolls, but are not limited in the number of dice that can be bought in this way.

.Example
[caption =  ""]
====
A [lexicWord]#character# is facing an enemy of a similar power level, but she decides nonetheless to run rather than confront him.
The [lexicWord]#player# asks the [lexicWord]#GM# to call upon her [lexicWord]#character's# [lexicWord]#prudence#.
The [lexicWord]#GM# agrees that running from this enemy is a cowardly thing to do, so he allows the roll.
The [lexicWord]#character# is leaning towards [lexicWord]#craven / prudent# so the [lexicWord]#dice-pool# will be of 1d10.
An additional die could be added to the [lexicWord]#dice-pool# by spending 1 [lexicWord]#spirit point#.
Alternatively, two dice could be added by spending 3 [lexicWord]#spirit points# (1 + 2), or three dice for 6 [lexicWord]#spirit points# (1 + 2 + 3), etc.
====

For every [lexicWord]#MoSes# obtained on the [lexicWord]#virtue roll#, the [lexicWord]#player# can add 1 die to every [lexicWord]#dice-pool# that supports the [lexicWord]#character# acting accordingly to the end of the spectrum of the virtue called upon.
On the other hand, an equivalent [lexicWord]#malus# will be applied to every roll going against the [lexicWord]#virtue# called upon.

Those [lexicWord]#bonuses# and [lexicWord]#maluses# will last until the scene end.

.Example
[caption = ""]
====
The [lexicWord]#player# makes her [lexicWord]#craven / prudent# roll.
She decided to add two dice to her [lexicWord]#dice-pool#, bringing it to 3d10, and obtained 4 [lexicWord]#MoSes#.
This will allow her to add 4 dice to every [lexicWord]#dice-pool# to run away, hide or any other activity with the objective of avoiding the conflict (at the discretion of the [lexicWord]#GM#).

If for some reason, inside the same scene, the [lexicWord]#character# has to change strategy, face the enemy and act bravely, every roll supporting this new attitude will have 4 [lexicWord]#MoSes# subtracted from its result.
====

At the end of the scene, if the [lexicWord]#character# achieved his goal in a way supporting the end of the spectrum called upon, he will regained a number of [lexicWord]#spirit points# equal to the size of the dice rolled for the [lexicWord]#virtue roll# and the [lexicWord]#virtue# is moved one step towards the extreme impersonated.
If this is not judged to be the case, the [lexicWord]#virtue# of the [lexicWord]#character# will be moved towards the opposite extreme of what has been called upon.
He will also lose a number of [lexicWord]#spirit points# equal to the size of the dice used for the [lexicWord]#virtue roll#.

.Example
[caption = ""]
====
If our earlier [lexicWord]#character# manages to avoid the combat by running away or hiding, at the end of the scene, she will regain 10 [lexicWord]#spirit points# and her [lexicWord]#courage# will be move one step toward [lexicWord]#craven/prudent#, birnging it to the complete lack of the [lexicWord]#virtue#.

If the scene is resolved in a different manner, if there is a confrontation or if it conclude at the disadvantage of the [lexicWord]#character#, this last one will lose 10 [lexicWord]#spirit points# and her [lexicWord]#virtue# will be moved one step towards [lexicWord]#daring/reckless#, bringing her to [lexicWord]#balanced#.
====

Calling upon a [lexicWord]#virtue# can grant a powerful advantage, but committing to one extreme interpretation of a [lexicWord]#virtue# is also inherently risky.

== Courage

[lexicWord]#Bravery# represent the way a [lexicWord]#character# will react in face of danger and their tolerance towards risk.

=== Craven / Prudent

Only a fool would rush into danger without thinking twice about it,
[lexicWord]#Prudent characters# know when it is best to avoid a perilous situation.
If they're truly [lexicWord]#craven#, this will be every threatening situations.

They can call upon their [lexicWord]#craven/prudent# when they want to avoid a risky situation.
It could be to avoid a combat by hiding or even yielding.
It could also be called upon for situations take extra precautions to reduce the inherent danger of a situation, like taking the time to securely rope the party before walking on a narrow ledge.

If after calling upon their [lexicWord]#craven/prudent# they have to change their approach and face the danger, their [lexicWord]#bonus# will be changed into [lexicWord]#malus#.

=== Daring / Reckless

The quintessential quality of heroes, many will overlook the folly of a [lexicWord]#character# blindly facing danger and admire his bravery.

[lexicWord]#Daring/reckless# can be called upon when undertaking significantly risky tasks without taking proper precautions or when facing an overwhelming enemy force.

It is not appropriate to call upon this [lexicWord]#virtue# to attack an inferior force or to perform an enterprise with a calculated and reasonable risk.
It should be reserved for when the [lexicWord]#character's# life is on the line (or at least for when they risk severe bodily harm).

If the [lexicWord]#character# realizes than he bit more than he could chew and now desire to mitigate risk, his [lexicWord]#bonus# will be changed into a [lexicWord]#malus#.

== Faith

Traditionally, in medieval-fantastic setting, [lexicWord]#faith# play an integral part in the life of most people.
The fact that there is some form of divine magic would imply that some form of divinity do exist, but doesn't not necessarily imply that everybody will worship or even worship it.

=== Iconoclast / Skeptic

A [lexicWord]#skeptic character# will have doubt towards the existence of the gods, or if confronted with their reality, will question if they are truly divine.
He might recognise them as powerful entity, but reject the claim that they are immortal, all powerful, omniscient or other extraordinary claim made about them.

The [lexicWord]#iconoclast# will not only resist worship but will oppose every form of it.

A [lexicWord]#player# can call upon his [lexicWord]#character's Iconoclast/Skeptic# if this one is acting against an organized religion or cult, in a way to disprove superstitious beliefs or directly against a divinity (or someone claiming to be).

Again, if the situation change and the [lexicWord]#character# realizes the error of his way, the [lexicWord]#bonus# he had will turn to a [lexicWord]#malus#.

=== Devout / Zealot

While the average person will follow the major tenets of their faith, the [lexicWord]#devotee# will pay attention to even the smallest and more obscure principles.

The [lexicWord]#zealot# might even gets thing further and try to impose his faith, all the way to the minima; details, on people around him.

[lexicWord]#Devoted/zealot# can be called upon if the [lexicWord]#character# is acting in a way that promote their faith.
If their resolve fluster and they have to infringe upon the dictates they should follow, the [lexicWord]#bonus# they gained is turned into a [lexicWord]#malus#.

== Honesty

Not everybody has the same relationship with the truth.
Some will hold it as the most sacred principle, while other will see it only as necessary as it is convenient.

=== Devious / Cunning

The [lexicWord]#cunning character# will know how to use half truths and full lies to reach his goals, however commendable or ignoble those are.
None should trust a fully [lexicWord]#devious character#; the problem being that he will be quite able at hiding their chicaneries.

[lexicWord]#Devious/cunning# can be called upon when lying, deceiving or being sly.
If the [lexicWord]#character# finally decides to submit to the truth, the bonus he had to pass his lies as facts will now be a malus to have his message accepted as real.

=== Frank / Pedantic

The [lexicWord]#frank character# will tend to favour the truth, even when this one is harsh or unpleasant.
If he's [lexicWord]#pedantic#, he will be obsessed with the accuracy of the facts, all the way to their smaller details.
For him, a mistake in the minutia of a fact can be seen the same as an outright lie.

[lexicWord]#Frank/pedantic# can be called upon when the [lexicWord]#character# is trying to convince someone he is telling the truth or worthy of trust.

If the [lexicWord]#character# wants to be less than truthfull after calling upon this virtue, the [lexicWord]#bonus# he was granted will be turned into a [lexicWord]#malus#.

== Pride

It is good for one to be aware of their worth, but it is not easy to properly asses it.

=== Meek / Humble

People will tend to think that the [lexicWord]#humble character# underestimates his importance.
If this is brought to the point of being [lexicWord]#meek#, the [lexicWord]#character# might feels like he have no value at all.

[lexicWord]#Meek/humble# can be called upon when a [lexicWord]#character# tries to resist provocation or [lexicWord]#taunt# or to make himself pass as insignificant.

=== Dignified / Vain

[lexicWord]#Dignified characters# know how to present themselves to command respect without crossing the line and being seen as [lexicWord]#vain#.

[lexicWord]#Dignified/Vain# can be called upon to resist [lexicWord]#intimidation# or if the [lexicWord]#character# has to save face.

If, in the end, the [lexicWord]#character# decide to belittle himself, the [lexicWord]#bonus# is turned into a [lexicWord]#malus#.

== Temperance

There is multiple competing theory of how much should one indulge in carnal pleasure.
[lexicWord]#Temperance# reflects a [lexicWord]#character's# position to this question.

=== Debauched / Epicurean

The [lexicWord]#epicurean character# sure knows how to enjoy the good things of life; the [lexicWord]#debauched# one, doesn't know how to resist them.

[lexicWord]#Debauched/Epicurean# can be called upon when the [lexicWord]#character# is merrymaking, feasting or partaking in other pleasures of the flesh.
It can also be called upon to help convince other of indulging.

If the [lexicWord]#character# judges that the situation slipped into extravagant luxury and wants to moderate himself, the [lexicWord]#bonus# he obtained will now be treated as a [lexicWord]#malus#.

=== Disciplined / Insensitive

[lexicWord]#Disciplined characters# will make a point of controlling their behaviour and resist temptation.
If they push it to the point of being [lexicWord]#insensitive#, they might become detached from simple pleasures.

[lexicWord]#Disciplined/insensitive# can be called upon to resist temptation or to endure hardship (lack of sleep, hunger, bitter cold, blistering heat, etc).

If, after closing himself to sensual pleasures, a [lexicWord]#character# wants to enjoy the good life, the [lexicWord]#bonus# he was granted will now be treated as [lexicWord]#malus#.
