= Basic Rules
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2018-08-22
:root: ../
:description: This is a summary of the basic rules.  It should aim to fit on 2 pages.
include::{root}Include.adoc[]

.{sidebarTitle}Basic Rules
[sidebar]
****
* Every [lexicWord]#character# is defined by six [lexicWord]#attributes#:, [lexicWord]#Agility#, [lexicWord]#Constitution#, [lexicWord]#Strength#, [lexicWord]#Erudition#, [lexicWord]#Persona# and [lexicWord]#Wisdom#.

* A multitude of [lexicWord]#skills# determine the different level of competency of the [lexicWord]#character# at different tasks.

** Skills are grouped together in [lexicWord]#groups# of 4 to 6.

* When a [lexicWord]#character# attempts a task that could result in a failure, a test is in order.

** This test is made by rolling a [lexicWord]#dice-pool# composed of a number of dice equals to the [lexicWord]#rank# of the [lexicWord]#skill# associated with the task plus the [lexicWord]#rank# of the [lexicWord]#group# it is part of, plus 1.

** The type of dice to be used cannot have more faces than the [lexicWord]#rank# of the [lexicWord]#attribute# governing the [lexicWord]#skill#.

** Every dice can grant a certain number of [lexicWord]#Measure of success (MoS)# depending on the value they show:

*** Between 4 and 7 (inclusively) grants 1 [lexicWord]#MoS#.

*** Between 8 and 11 (inclusively) grants 2 [lexicWord]#MoSes#.

*** Between 12 and 15 (inclusively) grants 3 [lexicWord]#MoSes#.

*** Between 16 and 19 (inclusively) grants 4 [lexicWord]#MoSes#.

*** a 20 grants 5 [lexicWord]#MoSes#.

** If the number of [lexicWord]#MoSes# equal or surpass a [lexicWord]#diffiuclty level# determined by the [lexicWord]#GM#, the task is successful.

*** Easy tasks require 1 [lexicWord]#MoS#.

*** Moderate tasks require 2 to 3 [lexicWord]#MoSes#.

*** Difficult tasks require 4 to 5 [lexicWord]#MoSes#.

*** Very difficult tasks require 6 to 7 [lexicWord]#MoSes#.

*** Near impossible tasks require 8 to 9 [lexicWord]#MoSes#.

*** Legendary tasks require 10 or more [lexicWord]#MoSes#.

** [lexicWord]#MoSes# over the [lexicWord]#difficulty level# are called [lexicWord]#hits# and can impact the result of a task.

* Different situations can call for different types of test.

** [lexicWord]#Static tests# have a simple [lexicWord]#difficulty level# and must be beaten in a single [lexicWord]#roll#.

** [LexicWord]#Opposed tests# involves two [lexicWord]#characters#, each rolling their own [lexicWord]#dice-pool#.
+
The [lexicWord]#character# with the most [lexicWord]#MoSes# succeed.
+
The difference in [lexicWord]#MoSes# between the two rolls are the [lexicWord]#hits# of the winner.

** [lexicWord]#Open-ended tests# don't have a [lexicWord]#difficulty level# to beat, but the number of [lexicWord]#MoSes# will influence how well a task is performed.

** [lexicWord]#Rolling tests# can be made with multiple [lexicWord]#dice-pools#, adding the [lexicWord]#MoSes# together to beat the [lexicWord]#difficulty level#.

*** [lexicWord]#First fail rolling test# will fail if one roll result in no [lexicWord]#MoS# before beating the [lexicWord]#difficulty level#.

*** [lexicWord]#Setback rolling test# will not fail if a roll result in no [lexicWord]#MoS#, but no progress will be made.

** [lexicWord]#Assisted test# are for situations where [lexicWord]#characters# can work together.
+
They each roll their own [lexicWord]#dice-pool# and add their [lexicWord]#MoSes# together to beat the [lexicWord]#difficulty level#.

*** [lexicWord]#Halved assisted tests# are like [lexicWord]#assisted tests# but the assisting [lexicWord]#characters# will only add half their [lexicWord]#MoSes# to those of the main [lexicWord]#character# undertaking the task.

** [lexicWord]#Group tests# are used for when multiple [lexicWord]#characters# attempt the same task, can assist each other in succeeding, but will succeed or fail individually.
+
[lexicWord]#Characters# can transfer part of their [lexicWord]#MoSes# to each other.

** [lexicWord]#Composed tests# are for complex tasks relying on two different [lexicWord]#skills#.
+
At least two rolls must be made, one with each [lexicWord]#skill#, and their [lexicWord]#MoSes# are added together.

** [lexicWord]#Mixed tests# are two or more of the previous types of tests combined together.

* Some circumstances can give [lexicWord]#bonuses# to a roll.
+
They will add dice to the [lexicWord]#character's# [lexicWord]#dice-pool#.

* Other circumstances will impose [lexicWord]#maluses# to a roll, subtracting [lexicWord]#MoSes# from the result.

* When every dice in a [lexicWord]#roll# with a complete [lexicWord]#dice-pool# show at least one [lexicWord]#MoS# and the attempted task is successful, this is considered a [lexicWord]#flawless successes#.

** The [lexicWord]#player# who rolled the [lexicWord]#flawless success# can chose to either regain one [lexicWord]#spirit point# per [lexicWord]#MoS# on the roll or to gain one [lexicWord]#experience point# in the [lexicWord]#skill# rolled.

* If a roll grants no [lexicWord]#MoSes#, it is considered a [lexicWord]#complete failure#.
+
This will have the [lexicWord]#player# rolls an [lexicWord]#ego test# with a [lexicWord]#difficulty level# equals to the [lexicWord]#rank level# of the failed [lexicWord]#skill#.

** If the [lexicWord]#ego test# is successful, the failed [lexicWord]#skill# gains one [lexicWord]#experience point#.

** If the [lexicWord]#ego test# fails, the [lexicWord]#character# loses a number of [lexicWord]#spirit points# equal to the [lexicWord]#rank# of the failed [lexicWord]#skill#.

* A [lexicWord]#dice-pool# can never contains more [lexicWord]#dice# than the current amount of [lexicWord]#spirit points# held by the [lexicWord]#character#.

** A [lexicWord]#player# can add dice to a [lexicWord]#dice-pool# by spending an amount of [lexicWord]#spirit points# equal to the number of dice currently in the [lexicWord]#dice-pool#.
+
A [lexicWord]#dice-pool# can be doubled in this way.

** A full night of sleep allows a [lexicWord]#character# to double his remaining [lexicWord]#spirit points#, up to his maximum.

* [LexicWord]#Skills# and [lexicWord]#attributes# each gain their own [lexicWord]#experience points#.

** [lexicWord]#Skills# are increased by spending a number of its [lexicWord]#experience points# equal to 1 plus its [lexicWord]#rank# (including the [lexicWord]#rank# of its [lexicWord]#group#), multiplied by 4.

** [lexicWord]#Skills group# are increased by subtracting one rank from 3 of its [lexicWord]#skills#.

* [lexicWord]#Characters# are ranked on five [lexicWord]#virtues#, each on a spectrum between the lack and the excess of it.

** [lexicWord]#Players# can call upon their [lexicWord]#character's virtues# if they're in a situation where they want to act in accordance to one of the extreme of the [lexicWord]#virtues#.

** They can make a [lexicWord]#virtue roll# to gain a [lexicWord]#bonus# to every actions in accordance to the side of the [lexicWord]#virtue# called upon for the duration of the scene.

** The [lexicWord]#dice-pool# for the [lexicWord]#virtue roll# is composed of one die by default.

** The type of dice is determined by the ranking on the spectrum of the virtue; the closer to the end being called upon the bigger the die.
+
The spectra are divided in 6 steps (including two balanced step), presented here with the die granted for calling on the lack of the [lexicWord]#virtue# / the excess of it:

*** Complete lack (d12 / d4)

*** Lack (d10 / d6)

*** Balanced (d8 / d8)

*** Balanced (d8 / d8)

*** Excess (d6 / d10)

*** Complete excess (d4 / d12)

** Additional dice can be purchased with [lexicWord]#spirit points# in the same way as for [lexicWord]#skill dice-pools# except that there is no limit on the number of dice that can be purchased.

** The five virtues and their spectrum are the following:

*** [lexicWord]#Courage#: Craven -> Prudent -> Brave -> Daring -> Reckless

*** [lexicWord]#Faith#: Iconoclast -> Skeptic -> Faithful -> Devout -> Zealot

*** [lexicWord]#Honesty#: Devious -> Cunning -> Honest -> Frank -> Pedantic

*** [lexicWord]#Pride#: Meek -> Humble -> Proud -> Dignified -> Vain

*** [lexicWord]#Temperance#: Debauched -> Epicurean -> Mild -> Disciplined -> Insensitive

* The rhythm at which play is happening is divided in three tempo:

** [lexicWord]#Action#, for when [lexicWord]#initiative# has been rolled and the order of operations are track precisely.

** [lexicWord]#Reaction#, for when the deeds of the [lexicWord]#characters# are resolved one after the other, as their intention is expressed, but the exact timing is not so important.

** [lexicWord]#Transition#, for in-between scene, when multiple tasks can be undertaken and resolved in a deferred way.

****
