= Labouring
//:author: Max Boivin
//:email: <max.boivin@winterdawn.com>
:revnumber: v0.0.1
:revdate: 2018-09-05
:root: ../../
:description: This is the Labouring skill individual file.
include::{root}Include.adoc[]

.*_Attributes: Constitution or Strength_*

[lexicWord]#Labouring# is a catch-all [lexicWord]#skill# for hard physical work that doesn't require an extensive amount of technical knowledge to be executed.
It will usually be repetitive labour that ruin the back and bore the mind.

== Mining and Digging Holes

It could be to prepare latrines, to mines for precious material or to lay a trap, digging a hole is an unpleasant but often time necessary task.
The speed at which a hole can be dug will depends on the material being dug in.
The time given below assume the [lexicWord]#character# digging is using the appropriate tools.

* Digging 1m³ in dirt or sand: 6 [lexicWord]#MoSes#
* Mining 1m³ in rock: 9 [lexicWord]#MoSes#

Digging and mining is done via [lexicWord]#step-back rolling labouring test#, each [lexicWord]#roll# representing an hour of work.
This [lexicWord]#test# can be [lexicWord]#assisted#.

Some circumstances can impose a [lexicWord]#malus# of the [lexicWord]#rolls#.
Densely pack ground or ground rich in clay could grant a 1 [lexicWord]#MoS malus# while digging.
Digging in a ground full of rocks or roots could grant a 2 [lexicWord]#MoSes malus#.
Mining into hard rock, like marble, could grant a 1 [lexicWord]#MoS malus#, while very hard rock, like granite, could grant a 2 [lexicWord]#MoSes malus#.

Scoring a negative result on a [lexicWord]#roll# mean the tool used gets damaged or break.

A [lexicWord]#character# can dig or mine less than a metre cube; if a only a small hole is dug, it might not be necessary to have the [lexicWord]#player# rolls.

Situations where digging or mining could be interesting enough to require [lexicWord]#rolls# would include a [lexicWord]#character# trying to dispose of a body, create a pit trap, tunnel under a castle or dig up a treasure, all those under time pressure.

== Tiling the Ground

Getting the ground properly ready for seeding is primordial to have a good crop yield.

The amount of ground a [lexciWord]#character# can tilt in a hour depend on the condition of the terrain.

* Ground that has been tilted the year before: 2m² per [lexicWord]#MoSes#
* Ground that hasn't been broken before: 1m² per [lexicWord]#MoSes#

Every [lexicWord]#roll# represents an hour of work.

If it is new ground and it is stony, 1 [lexicWord]#MoS malus# should be imposed.
This [lexicWord]#malus# should be raised to 2 [lexicWord]#MoSes# if the ground is full of roots.

If a [lexicWord]#roll# end up with a negative amount of [lexicWord]#MoSes# once the [lexicWord]#malus# is applied, the tool of the [lexicWord]#character# is damaged or breaks.

== Chopping Wood

If a [lexicWord]#character# needs to stock up on firewood for winter, this can be done with a [lexicWord]#labouring test#.
To prepare a stère (1m³) of wood, 10 [lexicWord]#MoSes# need to be accumulated on a [lexicWord]#step-back rolling test#, each [lexicWord]#roll# taking 1 hour.

Gathering trees in order to build a log cabin would also be a [lexicWord]#labouring# task.
Building a small cabin would require about 40 average size trees (about 30cm diameter).
You can gather those trees by doing a [lexicWord]#step-back rolling labouring test#, each [lexicWord]#roll# representing 2h of work.
Those [lexicWord]#roll# can be [lexicWord]#assisted#.
For every [lexicWord]#MoS# scored, 1 tree is cut down, delimbed and transported to a pile.

Remember that for building a long lasting log cabin or to produce proper firewood, the wood needs to be seasoned before use.

If a [lexicWord]#character# wants to cut a tree in [lexicWord]#action time#, an average tree should be cut down with 60 [lexicword]#MoSes#.
This can take quite a long time if done during combat and will occupy a [lexicWord]#character# for a long time (and might not be the funnest thing for the [lexicWord]#player#).

Chopping wood requires a tree felling axe.
If a [lexicWord]#character# tries to do so without an other type of axe (a fighting axe for example), a 1 [lexicWord]#MoS malus# could be imposed.
If he is using a non-axe type of blade, the [lexicWord]#malus# should be of 2 [lexicWord]#MoSes#.
In case of a [lexicWord]#roll# resulting with negative [lexicWord]#MoSes#, the tool used could be damaged or broken.

For gathering wood for a campfire, [lexicWord]#foraging# would be more appropriate.
